(() => {
  'use strict';
  const APP = { id: 'vertex', name: 'Vertex', url: 'https://vertexmath.vercel.app', feedbackUrl: 'https://tally.so/r/gDEWa1', premiumUrl: 'https://tally.so/r/44MPBB' };
  const DASHBOARDS = [{ key: 'accelerated-geometry', title: 'Accelerated Geometry', description: 'Choose a concept and start practicing.', order: 1 }];
  const MODULES = [];
  const ADMIN_PASSWORD_HASH = '95f756a4e50df1f4530386f40dc6f160e717f4420cc315ad36cfc94dd0d4ae14';
  const ADMIN_COOKIE = 'vertex_admin_session_v1';
  const ADMIN_QUEUE_COOKIE = 'vertex_admin_question_queue_v1';
const ADMIN_EXPORT_TALLY_URL = 'https://tally.so/r/WOLPQQ';
  const STORAGE_KEY = 'vertex_math_v1_state';
  const $ = (id) => document.getElementById(id);
  const getModulesForDashboard = (dashboardKey) => MODULES.filter((module) => module.dashboardKey === dashboardKey).sort((a, b) => a.order - b.order);
  const getState = () => { try { const state = JSON.parse(localStorage.getItem(STORAGE_KEY)); return state && DASHBOARDS.some((item) => item.key === state.dashboardKey) ? state : { dashboardKey: DASHBOARDS[0].key }; } catch (_) { return { dashboardKey: DASHBOARDS[0].key }; } };
  const saveState = (state) => localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  const state = getState();
  let currentQuestion = null;
  let premiumUnlocked = false;
  const isAdminRoute = /\/admin\/?$/.test(location.pathname) || new URLSearchParams(location.search).get('admin') === '1';
  let adminUnlocked = false;
  const readCookie = (name) => { const part = document.cookie.split('; ').find((item) => item.startsWith(`${name}=`)); return part ? decodeURIComponent(part.slice(name.length + 1)) : ''; };
  const writeCookie = (name, value, maxAge = 60 * 60 * 8) => { document.cookie = `${name}=${encodeURIComponent(value)}; max-age=${maxAge}; path=/; SameSite=Lax`; };
  const readAdminQueue = () => { try { const parsed = JSON.parse(readCookie(ADMIN_QUEUE_COOKIE) || '[]'); return Array.isArray(parsed) ? parsed : []; } catch (_) { return []; } };
  const writeAdminQueue = (queue) => { const raw = JSON.stringify(queue.slice(-24)); if (encodeURIComponent(raw).length > 3900) return false; writeCookie(ADMIN_QUEUE_COOKIE, raw, 60 * 60 * 24 * 365); return true; };
  const hashAdminPassword = async (value) => { const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return Array.from(new Uint8Array(bytes)).map((byte) => byte.toString(16).padStart(2, '0')).join(''); };
  const urlDashboard = new URLSearchParams(location.search).get('dashboard');
  if (urlDashboard && DASHBOARDS.some((item) => item.key === urlDashboard)) state.dashboardKey = urlDashboard;
  const dashboard = () => DASHBOARDS.find((item) => item.key === state.dashboardKey) || DASHBOARDS[0];
  function updateTitle() { document.title = `${APP.name} — ${dashboard().title}`; }
  function renderModules() { const modules = getModulesForDashboard(dashboard().key); $('moduleCount').textContent = modules.length; $('moduleList').innerHTML = modules.length ? modules.map((module) => `<article class="module-card"><strong>${module.title}</strong><p>${module.description || ''}</p></article>`).join('') : '<article class="module-empty"><strong>Your first module is coming soon.</strong><p>Accelerated Geometry has no modules yet.</p></article>'; }
  function syncAdminControls() { const queue = readAdminQueue(); const panel = $('adminExportPanel'); const remove = $('adminDeleteQuestionBtn'); const summary = $('adminQueueSummary'); if (panel) panel.hidden = !adminUnlocked; if (remove) remove.hidden = !adminUnlocked || !currentQuestion; if (summary) summary.textContent = queue.length ? `${queue.length} question${queue.length === 1 ? '' : 's'} queued for removal.` : 'No questions selected.'; }
  function syncDashboard() { const active = dashboard(); $('headerDashboard').textContent = active.title; $('dashboardTitle').textContent = active.title; $('dashboardDescription').textContent = active.description; updateTitle(); renderModules(); saveState(state); }
  function setMenu(open) { $('appSwitcherMenu').hidden = !open; $('appSwitcherButton').setAttribute('aria-expanded', String(open)); }
  function openFeedback() { $('feedbackForm').reset(); updateFeedbackType(); $('feedbackStatus').textContent = APP.feedbackUrl ? 'You will continue to a secure feedback form.' : 'Feedback delivery will be enabled when a Vertex form URL is configured.'; $('feedbackOverlay').hidden = false; $('feedbackMessage').focus(); }
  function closeFeedback() { $('feedbackOverlay').hidden = true; }
  function updateFeedbackType() { const requested = $('feedbackType').value === 'module_request'; $('requestedModuleField').hidden = !requested; $('requestedModule').required = requested; $('feedbackMessage').placeholder = requested ? 'What would you want to practice in this module, and what would make it useful?' : 'What should be improved?'; }
  async function refreshPremiumSession() { try { const response = await fetch('/api/premium/session', { credentials: 'same-origin' }); const data = await response.json(); premiumUnlocked = data.premium === true; } catch (_) { premiumUnlocked = false; } }
  function openPremium() { $('premiumForm').reset(); $('premiumRequestForm').reset(); $('premiumRequestForm').hidden = true; $('premiumStatus').textContent = premiumUnlocked ? 'Premium is already active on this device.' : 'Premium is verified securely when Vertex is deployed with its server configuration.'; $('premiumRequestStatus').textContent = ''; $('premiumOverlay').hidden = false; $('premiumPassword').focus(); }
  function closePremium() { $('premiumOverlay').hidden = true; }
  async function submitPremium(event) { event.preventDefault(); const status = $('premiumStatus'); try { const response = await fetch('/api/premium/verify', { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify({ password: $('premiumPassword').value }) }); if (!response.ok) throw new Error('That password could not be verified.'); premiumUnlocked = true; status.textContent = 'Premium unlocked for Vertex on this device.'; $('premiumForm').reset(); setTimeout(closePremium, 350); } catch (error) { status.textContent = error.message === 'That password could not be verified.' ? error.message : 'Premium verification is unavailable until Vertex is configured and deployed.'; } }
  function submitFeedback(event) { event.preventDefault(); const requested = $('requestedModule').value.trim(); const type = $('feedbackType').value; if (type === 'module_request' && !requested) { $('requestedModule').focus(); return; } if (!APP.feedbackUrl) { $('feedbackStatus').textContent = 'Feedback delivery is not configured yet; no information was sent.'; return; } const tallyType = ({ bug: 'Bug report', ui_request: 'UI request', improvement: 'Improvement request', module_request: 'New module request', feedback_system: 'Feedback about feedback system', general: 'Other' })[type] || 'Other'; const message = type === 'module_request' ? `Requested module: ${requested}\n\n${$('feedbackMessage').value.trim()}` : $('feedbackMessage').value.trim(); const url = new URL(APP.feedbackUrl); Object.entries({ form_type: 'feedback', app_name: APP.id, feedback_type: tallyType, requested_module: requested, message, email: $('feedbackEmail').value.trim(), level: dashboard().title, module: 'dashboard', source: 'feedback_button', dashboard: dashboard().title, page_url: location.href }).forEach(([key, value]) => { if (value) url.searchParams.set(key, value); }); window.open(url, '_blank', 'noopener,noreferrer'); $('feedbackStatus').textContent = 'Tally opened in a new tab. Submit your feedback there.'; }
  function submitPremiumRequest(event) { event.preventDefault(); if (!$('premiumRequestForm').reportValidity()) return; const url = new URL(APP.premiumUrl); Object.entries({ form_type: 'premium_access_request', app_name: APP.id, source: 'premium_modal', current_level: dashboard().title, current_module: 'dashboard', level: dashboard().title, module: 'dashboard', page_url: location.href, name: $('premiumRequestName').value.trim(), email: $('premiumRequestEmail').value.trim() }).forEach(([key, value]) => { if (value) url.searchParams.set(key, value); }); window.open(url, '_blank', 'noopener,noreferrer'); $('premiumRequestStatus').textContent = 'Tally opened in a new tab. Submit your request there.'; }
  function initAdminTools() { const gate = $('adminGateOverlay'); const form = $('adminGateForm'); const password = $('adminPasswordInput'); const status = $('adminGateStatus'); if (!isAdminRoute) { syncAdminControls(); return; } const unlock = () => { adminUnlocked = true; writeCookie(ADMIN_COOKIE, '1'); gate.hidden = true; syncAdminControls(); }; if (readCookie(ADMIN_COOKIE) === '1') unlock(); else gate.hidden = false; form?.addEventListener('submit', async (event) => { event.preventDefault(); const digest = await hashAdminPassword(password.value); if (digest === ADMIN_PASSWORD_HASH) { unlock(); status.textContent = ''; } else { status.textContent = 'That password is not valid.'; password.select(); } }); $('adminDeleteQuestionBtn')?.addEventListener('click', () => { if (!currentQuestion) return; const record = { app: 'vertex', dashboard: dashboard().key, module: currentQuestion.module || 'unknown', questionId: String(currentQuestion.id || ''), prompt: String(currentQuestion.prompt || '').replace(/<[^>]+>/g, '').trim(), expected: String(currentQuestion.expected || currentQuestion.answer || ''), options: Array.isArray(currentQuestion.options) ? currentQuestion.options : [], selectedAt: new Date().toISOString() }; const key = `${record.app}:${record.dashboard}:${record.module}:${record.questionId}`; const queue = readAdminQueue(); if (!queue.some((item) => `${item.app}:${item.dashboard}:${item.module}:${item.questionId}` === key) && !writeAdminQueue([...queue, record])) { $('adminExportStatus').textContent = 'The queue is full; export it before selecting more questions.'; return; } $('adminExportStatus').textContent = 'Question added to the removal queue.'; syncAdminControls(); }); $('adminExportBtn')?.addEventListener('click', () => { const queue = readAdminQueue(); const statusEl = $('adminExportStatus'); if (!queue.length) { statusEl.textContent = 'Select at least one question first.'; return; } if (!ADMIN_EXPORT_TALLY_URL) { statusEl.textContent = 'Admin export is ready, but the new Tally export-form URL still needs to be configured.'; return; } const url = new URL(ADMIN_EXPORT_TALLY_URL); Object.entries({ form_type: 'admin_question_removal', app_name: 'vertex', dashboard: dashboard().key, selected_questions: JSON.stringify(queue), source: 'admin_question_queue', page_url: location.href, email: 'clark.alden@lbusd.org' }).forEach(([key, value]) => url.searchParams.set(key, value)); window.open(url.toString(), '_blank', 'noopener,noreferrer'); statusEl.textContent = 'Tally opened in a new tab. Submit the export there.'; }); syncAdminControls(); }
  $('appSwitcherButton').addEventListener('click', () => setMenu($('appSwitcherMenu').hidden)); const dashboardMenu = $('dashboardSwitcherMenu'); const setDashboardMenu = (open) => { dashboardMenu.hidden = !open; $('dashboardSwitcherButton').setAttribute('aria-expanded', String(open)); }; $('dashboardSwitcherButton').addEventListener('click', () => setDashboardMenu(dashboardMenu.hidden)); document.addEventListener('click', (event) => { if (!$('appSwitcherButton').closest('.brand-wrap').contains(event.target)) setMenu(false); if (!$('dashboardSwitcherButton').closest('.dashboard-switcher').contains(event.target)) setDashboardMenu(false); }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape') { setMenu(false); setDashboardMenu(false); closeFeedback(); closePremium(); } }); $('feedbackButton').addEventListener('click', openFeedback); $('feedbackClose').addEventListener('click', closeFeedback); $('feedbackCancel').addEventListener('click', closeFeedback); $('feedbackType').addEventListener('change', updateFeedbackType); $('feedbackForm').addEventListener('submit', submitFeedback); $('premiumButton').addEventListener('click', openPremium); $('premiumClose').addEventListener('click', closePremium); $('premiumForm').addEventListener('submit', submitPremium); $('premiumRequestToggle').addEventListener('click', () => { $('premiumRequestForm').hidden = !$('premiumRequestForm').hidden; }); $('premiumRequestForm').addEventListener('submit', submitPremiumRequest);
  $('homeSettingsBtn').addEventListener('click', () => $('modulesHeading').scrollIntoView({ behavior: 'smooth', block: 'start' }));
  window.VertexApp = { APP, DASHBOARDS, MODULES, getModulesForDashboard, setDashboard(key) { if (DASHBOARDS.some((item) => item.key === key)) { state.dashboardKey = key; syncDashboard(); } } };
  syncDashboard();
  initAdminTools();
  refreshPremiumSession();
  window.VertexApp.setCurrentQuestion = (question) => { currentQuestion = question || null; syncAdminControls(); };
})();
