(() => {
  'use strict';
  const APP = { id: 'vertex', name: 'Vertex', url: 'https://vertexmath.vercel.app', feedbackUrl: 'https://tally.so/r/Pdq7AQ' };
  const DASHBOARDS = [{ key: 'accelerated-geometry', title: 'Accelerated Geometry', description: 'Build confidence with clear, focused geometry practice.', order: 1 }];
  const MODULES = [];
  const STORAGE_KEY = 'vertex_math_v1_state';
  const $ = (id) => document.getElementById(id);
  const getModulesForDashboard = (dashboardKey) => MODULES.filter((module) => module.dashboardKey === dashboardKey).sort((a, b) => a.order - b.order);
  const getState = () => { try { const state = JSON.parse(localStorage.getItem(STORAGE_KEY)); return state && DASHBOARDS.some((item) => item.key === state.dashboardKey) ? state : { dashboardKey: DASHBOARDS[0].key }; } catch (_) { return { dashboardKey: DASHBOARDS[0].key }; } };
  const saveState = (state) => localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  const state = getState();
  const dashboard = () => DASHBOARDS.find((item) => item.key === state.dashboardKey) || DASHBOARDS[0];
  function updateTitle() { document.title = `${APP.name} — ${dashboard().title}`; }
  function renderModules() { const modules = getModulesForDashboard(dashboard().key); $('moduleCount').textContent = modules.length; $('moduleList').innerHTML = modules.length ? modules.map((module) => `<article class="module-card"><strong>${module.title}</strong><p>${module.description || ''}</p></article>`).join('') : '<article class="module-empty"><strong>Modules are being prepared.</strong><p>Accelerated Geometry is ready for its first carefully designed module. No placeholder lessons have been added.</p></article>'; }
  function syncDashboard() { const active = dashboard(); $('headerDashboard').textContent = active.title; $('dashboardTitle').textContent = active.title; $('dashboardDescription').textContent = active.description; updateTitle(); renderModules(); saveState(state); }
  function setMenu(open) { $('appSwitcherMenu').hidden = !open; $('appSwitcherButton').setAttribute('aria-expanded', String(open)); }
  function openFeedback() { $('feedbackForm').reset(); updateFeedbackType(); $('feedbackStatus').textContent = APP.feedbackUrl ? 'You will continue to a secure feedback form.' : 'Feedback delivery will be enabled when a Vertex form URL is configured.'; $('feedbackOverlay').hidden = false; $('feedbackMessage').focus(); }
  function closeFeedback() { $('feedbackOverlay').hidden = true; }
  function updateFeedbackType() { const requested = $('feedbackType').value === 'module_request'; $('requestedModuleField').hidden = !requested; $('requestedModule').required = requested; $('feedbackMessage').placeholder = requested ? 'What would you want to practice in this module, and what would make it useful?' : 'What should be improved?'; }
  function openPremium() { $('premiumForm').reset(); $('premiumRequestForm').reset(); $('premiumRequestForm').hidden = true; $('premiumStatus').textContent = 'Premium is verified securely when Vertex is deployed with its server configuration.'; $('premiumRequestStatus').textContent = ''; $('premiumOverlay').hidden = false; $('premiumPassword').focus(); }
  function closePremium() { $('premiumOverlay').hidden = true; }
  async function submitPremium(event) { event.preventDefault(); const status = $('premiumStatus'); try { const response = await fetch('/api/premium/verify', { method: 'POST', headers: { 'Content-Type': 'application/json' }, credentials: 'same-origin', body: JSON.stringify({ password: $('premiumPassword').value }) }); if (!response.ok) throw new Error('That password could not be verified.'); status.textContent = 'Premium unlocked for Vertex on this device.'; $('premiumForm').reset(); } catch (error) { status.textContent = error.message === 'That password could not be verified.' ? error.message : 'Premium verification is unavailable until Vertex is configured and deployed.'; } }
  function submitFeedback(event) { event.preventDefault(); const requested = $('requestedModule').value.trim(); const type = $('feedbackType').value; if (type === 'module_request' && !requested) { $('requestedModule').focus(); return; } if (!APP.feedbackUrl) { $('feedbackStatus').textContent = 'Feedback delivery is not configured yet; no information was sent.'; return; } const tallyType = type === 'module_request' ? 'Feature Request' : 'Other'; const message = type === 'module_request' ? `Requested module: ${requested}\n\n${$('feedbackMessage').value.trim()}` : $('feedbackMessage').value.trim(); const url = new URL(APP.feedbackUrl); Object.entries({ form_type: 'feedback', app_name: APP.id, feedback_type: tallyType, requested_module: requested, message, email: $('feedbackEmail').value.trim(), level: dashboard().title, module: 'dashboard', source: 'feedback_button', dashboard: dashboard().title, page_url: location.href }).forEach(([key, value]) => { if (value) url.searchParams.set(key, value); }); window.open(url, '_blank', 'noopener,noreferrer'); $('feedbackStatus').textContent = 'Tally opened in a new tab. Submit your feedback there.'; }
  function submitPremiumRequest(event) { event.preventDefault(); const url = new URL('https://tally.so/r/Y5A1Oq'); Object.entries({ form_type: 'premium_access_request', app_name: APP.id, source: 'premium_request', current_level: dashboard().title, current_module: 'dashboard', page_url: location.href, name: $('premiumRequestName').value.trim(), email: $('premiumRequestEmail').value.trim() }).forEach(([key, value]) => { if (value) url.searchParams.set(key, value); }); window.open(url, '_blank', 'noopener,noreferrer'); $('premiumRequestStatus').textContent = 'Tally opened in a new tab. Submit your request there.'; }
  $('appSwitcherButton').addEventListener('click', () => setMenu($('appSwitcherMenu').hidden)); document.addEventListener('click', (event) => { if (!$('appSwitcherButton').closest('.brand-wrap').contains(event.target)) setMenu(false); }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape') { setMenu(false); closeFeedback(); closePremium(); } }); $('feedbackButton').addEventListener('click', openFeedback); $('feedbackClose').addEventListener('click', closeFeedback); $('feedbackCancel').addEventListener('click', closeFeedback); $('feedbackType').addEventListener('change', updateFeedbackType); $('feedbackForm').addEventListener('submit', submitFeedback); $('premiumButton').addEventListener('click', openPremium); $('premiumClose').addEventListener('click', closePremium); $('premiumForm').addEventListener('submit', submitPremium); $('premiumRequestToggle').addEventListener('click', () => { $('premiumRequestForm').hidden = !$('premiumRequestForm').hidden; }); $('premiumRequestForm').addEventListener('submit', submitPremiumRequest);
  window.VertexApp = { APP, DASHBOARDS, MODULES, getModulesForDashboard, setDashboard(key) { if (DASHBOARDS.some((item) => item.key === key)) { state.dashboardKey = key; syncDashboard(); } } };
  syncDashboard();
})();
