/* Vertex Geometry curriculum adapter. Source: scanned classroom PDFs in ../Canvas Geometry PDFs. */
(() => {
  'use strict';
  window.LearningAppShared?.registerUpdate({id:'vertex-geometry-3-5-2026-09',app:'vertex',title:'New: Lesson 3-5 practice',copy:'Practice equations of parallel and perpendicular lines in Vertex.',tourSteps:[{title:'Open Modules',copy:'Choose the new Lesson 3-5 section from Unit 3.',target:'modules'},{title:'Try a practice prompt',copy:'Work with parallel and perpendicular slopes, then write line equations.',target:'practice'}]});

  const MODULES = [
    { key:'geometry-1-1', unit:'unit-1', section:'1.1', name:'Points, Lines, and Planes', sources:['01-01_points-lines-planes_annotated.pdf'], premium:false },
    { key:'geometry-1-3', unit:'unit-1', section:'1.3', name:'Midpoint and Distance Formula', sources:['01-03_midpoint-and-distance-formula_annotated.pdf'], premium:false },
    { key:'geometry-1-5', unit:'unit-1', section:'1.5', name:'Measuring and Constructing Angles', sources:['01-05_measuring-angles_annotated.pdf','01-05_more-measuring-angles_annotated.pdf'], premium:false },
    { key:'geometry-1-6', unit:'unit-1', section:'1.6', name:'Pairs of Angles', sources:['01-06_pairs-of-angles_annotated.pdf'], premium:false },
    { key:'geometry-review', unit:'unit-1', section:'1.99', name:'Test 1 Review', sources:['01-99_review-for-test-1_answers.pdf'], premium:true },
    { key:'geometry-2-2', unit:'unit-2', section:'2.2', name:'Inductive and Deductive Reasoning', sources:['02-02_inductive-and-deductive-reasoning_part-1_annotated.pdf'], premium:false },
    { key:'geometry-2-4', unit:'unit-2', section:'2.4', name:'Algebraic Reasoning', sources:['02-04_algebraic-reasoning_annotated.pdf'], premium:false },
    { key:'geometry-2-5', unit:'unit-2', section:'2.5', name:'Proving Statements about Segments and Angles', sources:['02-05_proving-segments-and-angles_annotated.pdf'], premium:false },
    { key:'geometry-2-6', unit:'unit-2', section:'2.6', name:'Proving Geometric Relationships', sources:['02-06_proving-geometric-relationships_annotated.pdf'], premium:false },
    { key:'geometry-3-1', unit:'unit-3', section:'3.1', name:'Pairs of Lines and Angles', sources:['03-01_pairs-of-lines-and-angles_blank.pdf'], premium:false },
    { key:'geometry-3-2', unit:'unit-3', section:'3.2', name:'Parallel Lines and Transversals', sources:['03-02_parallel-lines-and-transversals_annotated.pdf'], premium:false, reduced:true },
    { key:'geometry-3-3', unit:'unit-3', section:'3.3', name:'Proofs with Parallel Lines', sources:['03-03_proofs-with-parallel-lines_annotated.pdf'], premium:true },
    { key:'geometry-3-4', unit:'unit-3', section:'3.4', name:'Proofs with Perpendicular Lines', sources:['03-04_proofs-with-perpendicular-lines_annotated.pdf'], premium:true },
    { key:'geometry-3-5', unit:'unit-3', section:'3.5', name:'Equations of Parallel and Perpendicular Lines', sources:['3.5 Equations of Parallel and Perpendicular Lines.pdf','3.5 Equations of Parallel and Perpendicular Lines - annotated-1.pdf'], premium:false },
    { key:'geometry-review-2', unit:'unit-3', section:'3.99', name:'Test 2 Review', sources:['03-99_review-for-test-2_answers.pdf'], premium:true },
    { key:'geometry-reference', unit:'reference', section:'Reference', name:'Theorems, Definitions, Postulates & Properties', sources:['00_geometry-sequence_highlighted.pdf','01-01_points-lines-planes_annotated.pdf','01-03_midpoint-and-distance-formula_annotated.pdf','01-05_measuring-angles_annotated.pdf','01-05_more-measuring-angles_annotated.pdf','01-06_pairs-of-angles_annotated.pdf','01-99_review-for-test-1_answers.pdf','02-02_inductive-and-deductive-reasoning_part-1_annotated.pdf','02-04_algebraic-reasoning_annotated.pdf','02-05_proving-segments-and-angles_annotated.pdf','02-06_proving-geometric-relationships_annotated.pdf','03-01_pairs-of-lines-and-angles_blank.pdf','03-02_parallel-lines-and-transversals_annotated.pdf','03-03_proofs-with-parallel-lines_annotated.pdf','03-04_proofs-with-perpendicular-lines_annotated.pdf','03-99_review-for-test-2_answers.pdf'], premium:true }
  ];
  const byKey = Object.fromEntries(MODULES.map((module) => [module.key, module]));

  // Shared, conservative normalization: presentation differences are harmless, but
  // aliases remain explicit so incorrect mathematical answers are not accepted.
  const normalize = (value) => String(value ?? '').normalize('NFKC').toLowerCase()
    .replace(/[∠]/g,'angle ').replace(/[≅≡]/g,' congruent ').replace(/[√]/g,'sqrt ')
    .replace(/[×]/g,' x ').replace(/[÷]/g,' / ').replace(/[≤]/g,' less than or equal to ')
    .replace(/[≥]/g,' greater than or equal to ').replace(/[≠]/g,' not equal to ')
    .replace(/[±]/g,' plus or minus ').replace(/[°]/g,' degree ')
    .replace(/\bdegrees\b/g,'degree').replace(/([a-z])(?=\d)/g,'$1 ').replace(/(?<=\d)(?=[a-z])/g,' ')
    .replace(/(?<!\d)\.(?!\d)/g,' ').replace(/[^a-z0-9.+\-/\s]/g,' ').replace(/\s+/g,' ').trim();
  // Whitespace around arithmetic operators is presentation only; keep the
  // operator itself so +, -, and / still distinguish different answers.
  const normalizeAnswer = (value) => normalize(value).replace(/\b(point|angle|segment|unit|degrees?)\b/g,' $1 ').replace(/\s*([.+\-/])\s*/g,'$1').replace(/\s+/g,' ').trim();
  const answerSet = (answers) => new Set((answers || []).flatMap((answer) => { const value = normalizeAnswer(answer); return value ? [value] : []; }));
  const makeQuestion = (id, prompt, answer, aliases = [], options = {}) => ({
    id, mode:options.mode || 'text', prompt, expectedDisplay:answer,
    acceptable:answerSet([answer, ...aliases]), explanation:options.explanation || 'Use the Geometry definition, postulate, property, or theorem from this section.',
    ...(options.mode === 'mcq' ? { options:options.options, correctIndex:options.options.indexOf(answer) } : {})
  });
  const mcq = (id, prompt, answer, options, explanation) => makeQuestion(id, prompt, answer, [], { mode:'mcq', options, explanation });
  const text = (answer) => String(answer);
  const QUESTIONS = {
    'geometry-1-1': [
      mcq('u1-1-point','What undefined term names an exact location?','point',['point','line','plane','ray']), mcq('u1-1-line','What undefined term extends forever in two opposite directions?','line',['point','line','plane','ray']), mcq('u1-1-plane','What undefined term is a flat surface with two dimensions?','plane',['point','line','plane','angle']), mcq('u1-1-segment','A part of a line with two endpoints is a?','line segment',['line segment','ray','plane','angle']), mcq('u1-1-ray','A part of a line with one endpoint that extends forever in one direction is a?','ray',['line','ray','segment','plane']), mcq('u1-1-collinear','Points on the same line are called?','collinear points',['collinear points','coplanar points','opposite rays','skew lines']), makeQuestion('u1-1-coplanar','Points that lie in the same plane are called?','coplanar points',['coplanar','points in the same plane']), mcq('u1-1-opposite-rays','Two opposite rays with a common endpoint form a?','line',['line','segment','angle','plane']), mcq('u1-1-line-notation','Through two distinct points, there is exactly one ___.','line',['line','plane','ray','angle']), makeQuestion('u1-1-ray-order','For ray notation AB, what does the first letter A identify?','endpoint',['the endpoint','starting point','initial point','the starting point'])
    ],
    'geometry-1-3': [
      mcq('u1-3-midpoint','What formula finds the midpoint of A(x₁,y₁) and B(x₂,y₂)?','( (x₁+x₂)/2, (y₁+y₂)/2 )',['( (x₁+x₂)/2, (y₁+y₂)/2 )','(x₁+x₂, y₁+y₂)','(x₂-x₁, y₂-y₁)','√((x₂-x₁)²+(y₂-y₁)²)']), makeQuestion('u1-3-midpoint-numeric','What is the midpoint of J(-3,2) and K(9,2)?','(3,2)',['3, 2','(3, 2)']), makeQuestion('u1-3-other-endpoint','If M(-2,5) is the midpoint and H(-3,7) is one endpoint, what is the other endpoint?','(-1,3)',['-1, 3','(-1, 3)']), mcq('u1-3-distance','Which formula finds the distance between two coordinate points?','distance formula',['distance formula','midpoint formula','slope formula','point-slope formula']), mcq('u1-3-pythagorean','Which theorem can also find coordinate distance using horizontal and vertical legs?','Pythagorean Theorem',['Pythagorean Theorem','Angle Addition Postulate','Segment Addition Postulate','Vertical Angle Theorem']), makeQuestion('u1-3-distance-numeric','Find the distance between (2,5) and (4,-1). Give the exact answer.','2√10',['2 sqrt 10','sqrt 40','√40'])
    ],
    'geometry-1-5': [
      mcq('u1-5-acute','An angle measuring 35° is what type?','acute',['acute','right','obtuse','straight']), mcq('u1-5-right','An angle measuring exactly 90° is what type?','right',['acute','right','obtuse','straight']), makeQuestion('u1-5-obtuse','What range describes an obtuse angle?','greater than 90° and less than 180°',['90 to 180 degrees','between 90 and 180 degrees','more than 90 degrees and less than 180 degrees']), makeQuestion('u1-5-straight','A straight angle always measures?','180°',['180','180 degrees']), makeQuestion('u1-5-addition','If D is inside ∠ABC, what postulate gives m∠ABD + m∠DBC = m∠ABC?','Angle Addition Postulate',['Angle Addition']), makeQuestion('u1-5-bisector','If BD bisects ∠ABC, what equality of measures is true?','m∠ABD = m∠DBC',['m angle abd = m angle dbc','m∠DBC = m∠ABD','m angle dbc = m angle abd']), makeQuestion('u1-5-congruent','If BD bisects ∠ABC, what congruence statement is true?','∠ABD ≅ ∠DBC',['angle abd congruent angle dbc','∠DBC ≅ ∠ABD','angle dbc congruent angle abd']), mcq('u1-5-angle-parts','In ∠ABC, which point is the vertex and which rays are its sides?','Vertex B; rays BA and BC',['Vertex B; rays BA and BC','Vertex A; rays AB and AC','Vertex C; rays CB and CA','Vertex B; rays AB and AC']), makeQuestion('u1-5-bisector-value','BD bisects ∠ABC. If m∠ABD = 4x+2 and m∠DBC = 3x+7, what is x?','5',['x = 5'])
    ],
    'geometry-1-6': [
      mcq('u1-6-vertical','Which angle relationship is always congruent?','vertical angles',['vertical angles','linear pairs','complementary angles','adjacent angles']), makeQuestion('u1-6-adjacent','Adjacent angles share a vertex and a common ___.','side',['common side','ray','common ray']), makeQuestion('u1-6-complementary','Complementary angles have measures that add to?','90°',['90','90 degrees']), makeQuestion('u1-6-supplementary','Supplementary angles have measures that add to?','180°',['180','180 degrees']), makeQuestion('u1-6-linear','Adjacent angles that form a line are a?','linear pair',['a linear pair','linear pair']), makeQuestion('u1-6-linear-properties','A linear pair is adjacent and its angles are what?','supplementary',['supplementary angles']), makeQuestion('u1-6-complement-example','If one complementary angle is 60°, what is the other?','30°',['30','30 degrees']), makeQuestion('u1-6-supplement-example','If one supplementary angle is 150°, what is the other?','30°',['30','30 degrees'])
    ],
    'geometry-review': [mcq('review-midpoint-mcq','A point that divides a segment into two congruent segments is its?','midpoint',['midpoint','angle bisector','transversal','endpoint']), mcq('review-collinear','Points A, B, and C lie on the same line. What term describes these points?','collinear',['collinear','coplanar','parallel','congruent']), makeQuestion('review-distance','What is the distance between (5,6) and (1,3)?','5 units',['5','5 unit']), mcq('review-angle-names','Rays QP, QR, and QS share endpoint Q, with QR between QP and QS. Which list names the two smaller angles and the whole angle?','∠PQR, ∠RQS, and ∠PQS',['∠PQR, ∠RQS, and ∠PQS','∠PQS, ∠RQS, and ∠PQR','∠PQR, ∠PQS, and ∠RQS','∠QPR, ∠QRS, and ∠QPS']), makeQuestion('review-linear','What postulate describes adjacent angles that form a line?','Linear Pair Postulate',['Linear Pair']), makeQuestion('review-supplement','If m∠WXY = (6x+59)° and m∠YXZ = (3x-14)° are supplementary, what is x?','15',['x = 15'])],
    'geometry-2-2': [mcq('u2-2-conjecture-mcq','An unproven statement based on observations is a?','conjecture',['conjecture','theorem','counterexample','postulate']), makeQuestion('u2-2-counterexample','What is an example that disproves a conjecture called?','counterexample',['a counterexample']), makeQuestion('u2-2-inductive','What kind of reasoning uses patterns or examples to form a conjecture?','inductive reasoning',['inductive','reasoning from patterns']), makeQuestion('u2-2-deductive','What kind of reasoning uses facts, definitions, postulates, and theorems?','deductive reasoning',['deductive','reasoning from established facts']), makeQuestion('u2-2-false','To disprove a universal conjecture, how many counterexamples are needed?','one',['1','one counterexample','a single counterexample']), mcq('u2-2-product','A conjecture says the product of any three negative integers is negative. Is it true or false?','true',['true','false'])],
    'geometry-2-4': [mcq('u2-4-segment','If B is between A and C, AB + BC = AC is the?','Segment Addition Postulate',['Segment Addition Postulate','Angle Addition Postulate','Substitution Property','Linear Pair Postulate']), mcq('u2-4-angle','Adjacent angle measures add to the whole angle by the?','Angle Addition Postulate',['Segment Addition Postulate','Angle Addition Postulate','Vertical Angle Theorem','Linear Pair Postulate']), mcq('u2-4-addition','If a=b, then a+c=b+c uses which property?','Addition Property of Equality',['Addition Property of Equality','Subtraction Property of Equality','Reflexive Property','Substitution Property']), makeQuestion('u2-4-subtraction','If a=b, then a-c=b-c uses which property?','Subtraction Property of Equality',['Subtraction Property']), makeQuestion('u2-4-multiplication','If a=b, then ac=bc uses which property?','Multiplication Property of Equality',['Multiplication Property']), makeQuestion('u2-4-division','If a=b and c≠0, then a/c=b/c uses which property?','Division Property of Equality',['Division Property']), makeQuestion('u2-4-substitution','What property permits replacing equal values in an equation?','Substitution Property of Equality',['Substitution Property']), makeQuestion('u2-4-reflexive','What property states a quantity is equal to itself?','Reflexive Property of Equality',['Reflexive Property']), makeQuestion('u2-4-symmetric','If a=b, then b=a uses which property?','Symmetric Property of Equality',['Symmetric Property']), makeQuestion('u2-4-transitive','If a=b and b=c, then a=c uses which property?','Transitive Property of Equality',['Transitive Property']), makeQuestion('u2-4-distributive','What property expands a(b+c) into ab+ac?','Distributive Property',['Distributive']), makeQuestion('u2-4-proof-columns','What are the two columns in a 2-Column Proof?','statements and reasons',['statement and reason','statements and reason'])],
    'geometry-2-5': [mcq('u2-5-reflexive','If AB ≅ AB, which property of congruence is shown?','Reflexive Property of Congruence',['Reflexive Property of Congruence','Symmetric Property of Congruence','Transitive Property of Congruence','Definition of Congruent Segments']), makeQuestion('u2-5-symmetric','If AB ≅ CD, then CD ≅ AB. Name the property.','Symmetric Property of Congruence',['Symmetric Property']), makeQuestion('u2-5-transitive','If AB ≅ CD and CD ≅ RT, then AB ≅ RT. Name the property.','Transitive Property of Congruence',['Transitive Property']), makeQuestion('u2-5-definition-segments','If AB ≅ CD, then AB = CD. Name the reason.','Definition of Congruent Segments',['Definition of Congruent Segment Lengths']), makeQuestion('u2-5-definition-angles','If ∠A ≅ ∠B, then m∠A = m∠B. Name the reason.','Definition of Congruent Angles',['Definition of Congruent Angle Measures']), mcq('u2-5-bisector','A segment bisector divides a segment into two what segments?','congruent segments',['congruent segments','parallel segments','adjacent angles','supplementary angles']), makeQuestion('u2-5-proof-given','In a proof, information supplied in the problem is called the?','given',['a given'])],
    'geometry-2-6': [mcq('u2-6-vertical-mcq','Which theorem proves vertical angles are congruent?','Vertical Angle Theorem',['Vertical Angle Theorem','Linear Pair Postulate','Congruent Supplements Theorem','Angle Addition Postulate']), makeQuestion('u2-6-supplements','What theorem says angles supplementary to the same angle are congruent?','Congruent Supplements Theorem',['Congruent Supplements']), makeQuestion('u2-6-complements','What theorem says angles complementary to the same angle are congruent?','Congruent Complements Theorem',['Congruent Complements']), makeQuestion('u2-6-linear-pair','What postulate says angles in a linear pair are supplementary?','Linear Pair Postulate',['Linear Pair']), makeQuestion('u2-6-transitive','Which property can connect ∠1 ≅ ∠3 and ∠3 ≅ ∠4 to prove ∠1 ≅ ∠4?','Transitive Property of Congruence',['Transitive Property']), makeQuestion('u2-6-proof-reason','In a two-column proof, definitions, postulates, theorems, and properties belong in the?','reasons column',['reason column'])],
    'geometry-3-1': [mcq('u3-1-parallel','Lines in the same plane that never intersect are?','parallel lines',['parallel lines','perpendicular lines','skew lines','transversal']), makeQuestion('u3-1-perpendicular','Lines that intersect to form right angles are?','perpendicular lines',['perpendicular']), makeQuestion('u3-1-skew','Lines that do not intersect and are not coplanar are?','skew lines',['skew']), makeQuestion('u3-1-transversal','A line that intersects two or more coplanar lines is a?','transversal',['a transversal']), makeQuestion('u3-1-intersecting-planes','Two planes that meet intersect in a?','line',['line of intersection']), makeQuestion('u3-1-nonparallel','When a transversal crosses two non-parallel lines, corresponding angles are not guaranteed to be what?','congruent',['equal'])],
    'geometry-3-2': [mcq('u3-2-alternate-interior','When parallel lines are cut by a transversal, alternate interior angles are?','congruent',['congruent','supplementary','complementary','vertical']), makeQuestion('u3-2-alternate-exterior','When parallel lines are cut by a transversal, alternate exterior angles are?','congruent',['congruent angles','equal']), makeQuestion('u3-2-corresponding','When parallel lines are cut by a transversal, corresponding angles are?','congruent',['congruent angles','equal']), makeQuestion('u3-2-consecutive-interior','When parallel lines are cut by a transversal, consecutive interior (same-side interior) angles are?','supplementary',['supplementary angles','add to 180 degrees']), makeQuestion('u3-2-consecutive-exterior','When parallel lines are cut by a transversal, consecutive exterior (same-side exterior) angles are?','supplementary',['supplementary angles','add to 180 degrees']), makeQuestion('u3-2-equation','Two adjacent angles form a linear pair and measure 120° and x°. What is x?','60',['x = 60']), makeQuestion('u3-2-corresponding-equation','When parallel lines are cut by a transversal, corresponding angles measure 120° and (3y+6)°. What is y?','38',['y = 38']), makeQuestion('u3-2-proof','Given k ∥ n, which theorem proves a pair of alternate interior angles congruent?','Alternate Interior Angles Theorem')],
    'geometry-3-3': [mcq('u3-3-converse-mcq','For two lines cut by a transversal, if corresponding angles are congruent, what can be concluded?','The lines are parallel',['The lines are parallel','The lines are perpendicular','The lines intersect at a right angle','The lines are skew']), makeQuestion('u3-3-transitive-parallel','If a ∥ b and b ∥ c, then a ∥ c. Name the theorem.','Transitive Property of Parallel Lines Theorem',['Transitive Property of Parallel Lines']), makeQuestion('u3-3-alt-interior-converse','For two lines cut by a transversal, if alternate interior angles are congruent, then the lines are?','parallel',['parallel lines']), makeQuestion('u3-3-alt-exterior-converse','For two lines cut by a transversal, if alternate exterior angles are congruent, then the lines are?','parallel',['parallel lines']), makeQuestion('u3-3-consecutive-interior-converse','For two lines cut by a transversal, if consecutive interior angles are supplementary, then the lines are?','parallel',['parallel lines']), makeQuestion('u3-3-consecutive-exterior-converse','For two lines cut by a transversal, if consecutive exterior angles are supplementary, then the lines are?','parallel',['parallel lines']), makeQuestion('u3-3-proof-reason','Given congruent corresponding angles formed by two lines and a transversal, which converse theorem proves the lines parallel?','Corresponding Angles Converse Theorem',['Corresponding Angles Converse']), makeQuestion('u3-3-equation','What value of x makes lines m and n parallel if (4(x+5))° and 72° are consecutive exterior angles?','22',['x = 22'])],
    'geometry-3-4': [mcq('u3-4-shortest-distance-mcq','The shortest distance from a point to a line is measured along a?','perpendicular segment',['perpendicular segment','parallel segment','angle bisector','transversal']), makeQuestion('u3-4-distance-formula','To find the length of the perpendicular from a point to a line, use the?','distance formula',['distance formula']), makeQuestion('u3-4-bisector','A perpendicular bisector passes through the segment midpoint at what angle?','a right angle',['90 degrees','90°','90']), makeQuestion('u3-4-parallel-perpendicular','In a plane, if a transversal is perpendicular to one of two parallel lines, then it is perpendicular to the?','other line'), makeQuestion('u3-4-same-line','In the same plane, if two lines are perpendicular to the same line, then they are?','parallel'), makeQuestion('u3-4-four-right-angles','Two intersecting perpendicular lines form how many right angles?','four',['4']), makeQuestion('u3-4-definition','A line that passes through a segment midpoint at a right angle is its?','perpendicular bisector',['perpendicular bisector line'])],
    'geometry-3-5': [mcq('line35-parallel-slope-mcq','What slope must a line have to be parallel to y = 5x + 3?','5',['5','-5','1/5','-1/5']), mcq('line35-parallel-point','Which equation describes the line through (4, 6) parallel to y = 5x + 3?','y = 5x - 14',['y = 5x - 14','y = 5x + 14','y = -5x + 26','y = 1/5x + 26/5']), makeQuestion('line35-perpendicular-slope','What is the slope of a line perpendicular to a line with slope -1/12?','12'), mcq('line35-perpendicular-point','Which equation describes the line through (2, -3) perpendicular to y = -6x + 10?','y = 1/6x - 10/3',['y = 1/6x - 10/3','y = -6x + 9','y = 6x - 15','y = 1/6x + 10/3']), mcq('line35-vertical','What is the equation of the vertical line through (3, -2)?','x = 3',['x = 3','y = 3','x = -2','y = -2']), mcq('line35-horizontal','What is the equation of the horizontal line through (4, 6)?','y = 6',['y = 6','x = 6','y = 4','x = 4']), makeQuestion('line35-parallel-compare','How do the slopes of distinct parallel nonvertical lines compare?','They are equal.',['they have the same slope']), makeQuestion('line35-perpendicular-compare','How do the slopes of perpendicular nonvertical lines compare?','They are negative reciprocals.',['their slopes are negative reciprocals','the product of their slopes is -1'])],
    'geometry-review-2': [mcq('review2-perpendicular-slope-mcq','What is the slope of a line perpendicular to a line with slope -1/12?','12',['12','-12','1/12','-1/12']), makeQuestion('review2-bisector-midpoint','What is the midpoint of P(4,-8) and Q(8,8)?','(6,0)',['6, 0']), mcq('review2-parallel-equation','Which equation describes the line through (4,6) parallel to y=5x+3?','y=5x-14',['y=5x-14','y=5x+14','y=-5x+26','y=1/5x+26/5']), mcq('review2-point-parallel','Which equation describes the line through (2,-3) parallel to y=-6x+10?','y=-6x+9',['y=-6x+9','y=-6x-9','y=6x-15','y=1/6x-10/3']), makeQuestion('review2-parallel-converse','Which theorem proves lines are parallel when corresponding angles are congruent?','Corresponding Angles Converse Theorem',['Corresponding Angles Converse']), makeQuestion('review2-perpendicular-distance','Find the exact distance from Q(-10,-4) to the line 5x-y=6.','2√26',['2 sqrt 26','sqrt 104','52/sqrt 26']), makeQuestion('review2-distance-point-line','What is the exact distance from P(5,-2) to the line through A(-3,-2) and B(1,2)?','4√2',['sqrt 32','√32']), makeQuestion('review2-proof-reason','Which theorem proves two lines parallel when corresponding angles are congruent?','Corresponding Angles Converse Theorem',['Corresponding Angles Converse'])],
    'geometry-reference': [mcq('ref-point-mcq','An exact location with no size or dimension is a?','point',['point','line','plane','ray']), mcq('ref-line-mcq','A set of points extending forever in two directions is a?','line',['point','line','segment','plane']), makeQuestion('ref-plane','A flat surface with no thickness extending in two dimensions is a?','plane'), makeQuestion('ref-conjecture','An unproven statement based on observations is a?','conjecture',['an unproven statement']), makeQuestion('ref-counterexample','An example that disproves a conjecture is a?','counterexample'), makeQuestion('ref-segment-addition','AB + BC = AC when B is between A and C is the?','Segment Addition Postulate'), makeQuestion('ref-angle-addition','m∠ABD + m∠DBC = m∠ABC is the?','Angle Addition Postulate'), makeQuestion('ref-vertical','Vertical angles are congruent by the?','Vertical Angle Theorem'), makeQuestion('ref-linear-pair','A linear pair is supplementary by the?','Linear Pair Postulate'), makeQuestion('ref-congruent-supplements','Angles supplementary to the same angle are congruent by the?','Congruent Supplements Theorem'), makeQuestion('ref-congruent-complements','Angles complementary to the same angle are congruent by the?','Congruent Complements Theorem'), makeQuestion('ref-definition-congruent','Congruent segments have equal lengths by the?','Definition of Congruent Segments'), makeQuestion('ref-reflexive','A quantity equal to itself uses the?','Reflexive Property of Equality'), makeQuestion('ref-symmetric','If a=b then b=a uses the?','Symmetric Property of Equality'), makeQuestion('ref-transitive','If a=b and b=c then a=c uses the?','Transitive Property of Equality'), makeQuestion('ref-distributive','a(b+c)=ab+ac is the?','Distributive Property'), makeQuestion('ref-parallel','Lines that never intersect in a plane are?','parallel lines',['parallel']), makeQuestion('ref-perpendicular','Lines that form right angles are?','perpendicular lines',['perpendicular']), makeQuestion('ref-transversal','A line intersecting two or more coplanar lines is a?','transversal',['a transversal']), makeQuestion('ref-corresponding','For parallel lines cut by a transversal, corresponding angles are?','congruent',['equal']), makeQuestion('ref-same-side','For parallel lines cut by a transversal, same-side interior angles are?','supplementary',['supplementary angles']), makeQuestion('ref-converse','The converse of a parallel-lines angle theorem is used to prove the lines are?','parallel',['parallel lines'])]
  };

  const poolFor = (app, key) => (QUESTIONS[key] || []).filter((item) => !app.state?.hiddenItems?.[item.id]);
  const enabledKeys = (app) => MODULES.filter((module) => !module.premium || app.hasPremiumAccess?.()).map((module) => module.key);
  const PREF_COOKIE = 'vertex_geometry_preferences_v1';
  const readPreferences = () => {
    try { const raw = document.cookie.split('; ').find((part) => part.startsWith(`${PREF_COOKIE}=`)); return raw ? JSON.parse(decodeURIComponent(raw.slice(PREF_COOKIE.length + 1))) : {}; } catch (_) { return {}; }
  };
  const writePreferences = (preferences) => { try { document.cookie = `${PREF_COOKIE}=${encodeURIComponent(JSON.stringify(preferences))}; max-age=31536000; path=/; SameSite=Lax`; } catch (_) {} };

  function installMathKeyboard() {
    const block = document.getElementById('textBlock'); const input = document.getElementById('answerInput');
    if (!block || !input || document.getElementById('vertexMathKeyboard')) return;
    const keyboard = document.createElement('div'); keyboard.id = 'vertexMathKeyboard'; keyboard.className = 'math-keyboard'; keyboard.setAttribute('aria-label','Math symbols');
    const symbols = ['√','π','°','×','÷','≤','≥','≠','±','⁄','x²'];
    keyboard.innerHTML = `<span class="math-keyboard-label">Math symbols</span>${symbols.map((symbol) => `<button type="button" class="btn small" data-math-symbol="${symbol}" aria-label="Insert ${symbol}">${symbol}</button>`).join('')}`;
    block.prepend(keyboard);
    keyboard.addEventListener('click', (event) => { const button = event.target.closest('[data-math-symbol]'); if (!button) return; const symbol = button.dataset.mathSymbol; const start = input.selectionStart ?? input.value.length; const end = input.selectionEnd ?? input.value.length; input.value = `${input.value.slice(0,start)}${symbol}${input.value.slice(end)}`; input.focus(); input.setSelectionRange(start + symbol.length, start + symbol.length); });
    window.VertexMathKeyboard = { insert:(symbol) => keyboard.querySelector(`[data-math-symbol="${symbol}"]`)?.click() };
  }

  function renderSettings(app) {
    const section = document.getElementById('moduleSettingsSection'); if (!section) return;
    const unlocked = !!app.hasPremiumAccess?.(); const preferences = readPreferences(); const saved = app.state?.geometryModules || preferences.modules || {};
    const markup = ['unit-1','unit-2','unit-3','reference'].map((unit) => {
      const label = unit === 'reference' ? 'Theorems, Definitions, Postulates & Properties' : `Unit ${unit.slice(-1)}`;
      const counts = { locked: 0, reduced: 0 };
      const cards = MODULES.filter((module) => module.unit === unit).map((module) => { const locked = module.premium && !unlocked; const kind = locked ? 'locked' : module.reduced ? 'reduced' : ''; const showBadge = kind && counts[kind] < (kind === 'locked' ? 1 : 2); if (showBadge) counts[kind] += 1; const description = locked ? 'Premium only: unlock this geometry section.' : module.reduced ? 'Free includes a smaller rotation; Premium adds the complete section.' : ''; const badge = showBadge ? `<button type="button" class="premium-badge premium-badge-${kind}" data-premium-lock="true" title="${description}" aria-label="${description}">${kind === 'locked' ? '🔒' : '◐'}</button>` : ''; return `<div class="toggle${locked ? ' module-locked' : ''}"><div><div class="label">${module.section} ${module.name} ${badge}</div><div class="desc">${module.sources.length} source PDF${module.sources.length === 1 ? '' : 's'} · ${QUESTIONS[module.key].length} questions${locked ? ' · Premium' : ''}</div></div><label><input type="checkbox" data-geometry-module="${module.key}" aria-label="Toggle ${module.name} module" ${saved[module.key] === true ? 'checked' : ''} ${locked ? 'disabled' : ''}><span class="switch" aria-hidden="true"></span></label></div>`; }).join('');
      return `<details class="module-group"${preferences.groups?.[unit] === true ? ' open' : ''}><summary>${label}</summary><div class="module-group-content">${cards}</div></details>`;
    }).join('');
    section.innerHTML = '<summary class="settings-section-summary">Geometry modules</summary>' + markup;
    section.querySelectorAll('[data-premium-lock]').forEach((button) => button.addEventListener('click', (event) => {
      event.preventDefault(); event.stopPropagation();
      document.querySelector('.shared-prompt-premium')?.remove();
      const settings = document.getElementById('settingsOverlay');
      if (settings) { settings.hidden = true; settings.style.display = 'none'; }
      const premium = document.getElementById('premiumOverlay');
      if (premium) { premium.hidden = false; premium.style.display = 'flex'; premium.style.zIndex = '1400'; }
      app.openPremiumAccess?.();
      if (premium) { premium.hidden = false; premium.style.display = 'flex'; premium.style.zIndex = '1400'; }
    }));
    section.querySelectorAll('[data-geometry-module]:not(:disabled)').forEach((box) => box.addEventListener('change', () => { app.state.geometryModules = Object.fromEntries([...section.querySelectorAll('[data-geometry-module]')].map((item) => [item.dataset.geometryModule, item.checked])); writePreferences({ ...readPreferences(), modules: app.state.geometryModules }); app.saveSoon(); app.updateHomeSummary?.(); }));
    section.querySelectorAll('details.module-group').forEach((group) => group.addEventListener('toggle', () => { const summary = group.querySelector('summary').textContent; const groups = { ...readPreferences().groups, [summary.startsWith('Theorems, Definitions') ? 'reference' : `unit-${summary.slice(-1)}`]: group.open }; writePreferences({ ...readPreferences(), groups }); }));
  }

  function labels() {
    document.title = 'Vertex — Accelerated Geometry'; document.documentElement.style.setProperty('--accent','#166534');
    document.querySelectorAll('#brandName, .app-switcher-menu a.is-current span').forEach((node) => { node.textContent = 'Vertex'; });
    ['subtitle','headerLevel','classSwitcherLabel'].forEach((id) => { const node = document.getElementById(id); if (node) node.textContent = 'Accelerated Geometry'; });
    const heading = document.querySelector('#homeCard h1'); if (heading) heading.textContent = 'Practice Accelerated Geometry';
    const lead = document.querySelector('#homeCard .home-intro'); if (lead) lead.textContent = 'Choose sections, then start a focused geometry session.';
    ['.dashboard-switcher','.level-switch','#spanish2Panel','#practiceOnlyRow','#practiceOnlyMobile','#soloSelect','#numbersSection','#numbersGuideOverlay','#summerPrepSettings','#practiceBehaviorSettings','#accentToolbar'].forEach((selector) => document.querySelectorAll(selector).forEach((node) => node.hidden = true));
    const levelPanel = document.getElementById('spanish1Panel'); if (levelPanel) levelPanel.hidden = false;
    const input = document.getElementById('answerInput'); if (input) input.placeholder = 'Type a geometry answer...';
    const enter = document.getElementById('enterPracticeBtn'); if (enter) { enter.innerHTML = 'Enter geometry session <span aria-hidden="true">→</span>'; enter.setAttribute('aria-label','Enter geometry session'); }
    const help = [...document.querySelectorAll('.settings-accordion')].find((node) => /Keyboard\s*&\s*Help/i.test(node.querySelector('summary')?.textContent || '')); if (help) { help.querySelector('summary').innerHTML = 'Geometry keyboard help <span class="summary-note">Optional</span>'; help.querySelector('.small.muted').textContent = 'Use the math symbol keyboard when notation is helpful. Enter submits your answer.'; }
  }

  function installProofBuilder() {
    const section = document.createElement('section'); section.className = 'proof-builder card'; section.id = 'proofBuilder'; section.setAttribute('aria-labelledby','proofBuilderTitle');
    section.innerHTML = `<h2 id="proofBuilderTitle">Complete a two-column proof</h2><p class="muted">Choose a proof exercise. The givens and goal are provided; fill each blank with a statement and its reason.</p><div class="proof-exercise-controls"><label>Exercise<select id="proofExercise"></select></label><button class="btn" id="proofHint" type="button">Hint</button><button class="btn" id="proofReset" type="button">Reset proof</button></div><div class="proof-problem"><div><small>GIVEN</small><p id="proofGiven"></p></div><div><small>PROVE</small><p id="proofGoal"></p></div></div><table class="proof-table"><thead><tr><th>#</th><th>Statement</th><th>Reason</th></tr></thead><tbody id="proofSteps"></tbody></table><div id="proofStatus" class="feedback neutral" aria-live="polite">Fill in each proof row, then check your work.</div><div class="proof-actions"><button class="btn primary" id="proofCheck" type="button">Check proof</button><button class="btn" id="proofShow" type="button">Show one solution</button></div>`;
    document.querySelector('#qaSection')?.after(section);
    const exercises = [
      { title:'Congruent segments', given:['AB ≅ CD'], prove:'AB = CD', rows:[['AB ≅ CD','Given'],['AB = CD','Definition of Congruent Segments']], hint:'Convert segment congruence into equality of lengths using the definition of congruent segments.' },
      { title:'Midpoint segments', given:['M is the midpoint of AB'], prove:'AM ≅ MB', rows:[['M is the midpoint of AB','Given'],['AM = MB','Definition of Midpoint'],['AM ≅ MB','Definition of Congruent Segments']], hint:'A midpoint divides a segment into equal lengths; equal lengths determine congruent segments.' },
      { title:'Angle bisector', given:['BD bisects ∠ABC'], prove:'∠ABD ≅ ∠DBC', rows:[['BD bisects ∠ABC','Given'],['m∠ABD = m∠DBC','Definition of Angle Bisector'],['∠ABD ≅ ∠DBC','Definition of Congruent Angles']], hint:'An angle bisector creates two equal angle measures. Equal measures mean congruent angles.' },
      { title:'Vertical angles', given:['∠1 and ∠2 are vertical angles'], prove:'∠1 ≅ ∠2', rows:[['∠1 and ∠2 are vertical angles','Given'],['∠1 ≅ ∠2','Vertical Angle Theorem']], hint:'Use the Vertical Angle Theorem.' },
      { title:'Linear pair', given:['∠1 and ∠2 form a linear pair'], prove:'∠1 and ∠2 are supplementary', rows:[['∠1 and ∠2 form a linear pair','Given'],['∠1 and ∠2 are supplementary','Linear Pair Postulate']], hint:'Use the Linear Pair Postulate.' },
      { title:'Equal segments by transitivity', given:['AB = CD','CD = EF'], prove:'AB = EF', rows:[['AB = CD','Given'],['CD = EF','Given'],['AB = EF','Transitive Property of Equality']], hint:'Two quantities equal to the same quantity are equal to each other.' },
      { title:'Parallel lines and corresponding angles', given:['ℓ ∥ m','∠1 and ∠2 are corresponding angles'], prove:'∠1 ≅ ∠2', rows:[['ℓ ∥ m','Given'],['∠1 and ∠2 are corresponding angles','Given'],['∠1 ≅ ∠2','Corresponding Angles Postulate']], hint:'Parallel lines cut by a transversal have congruent corresponding angles.' },
      { title:'Perpendicular lines', given:['ℓ ⟂ m','∠1 and ∠2 are adjacent angles formed by ℓ and m'], prove:'∠1 and ∠2 are supplementary', rows:[['ℓ ⟂ m','Given'],['m∠1 = 90°','Definition of Perpendicular Lines'],['m∠2 = 90°','Definition of Perpendicular Lines'],['m∠1 + m∠2 = 180°','Substitution Property of Equality'],['∠1 and ∠2 are supplementary','Definition of Supplementary Angles']], hint:'Perpendicular lines create right angles. Add the two 90° measures.' }
    ];
    const reasons=['Given','Definition of Congruent Segments','Definition of Congruent Angles','Definition of Midpoint','Definition of Angle Bisector','Vertical Angle Theorem','Linear Pair Postulate','Transitive Property of Equality','Substitution Property of Equality','Corresponding Angles Postulate','Definition of Perpendicular Lines','Definition of Supplementary Angles'];
    const exerciseSelect=section.querySelector('#proofExercise'), givenNode=section.querySelector('#proofGiven'), goalNode=section.querySelector('#proofGoal'), body=section.querySelector('#proofSteps'), status=section.querySelector('#proofStatus');
    exercises.forEach((exercise,index)=>{const option=document.createElement('option');option.value=String(index);option.textContent=exercise.title;exerciseSelect.append(option);});
    const redraw=()=>{const exercise=exercises[Number(exerciseSelect.value)]||exercises[0];givenNode.textContent=exercise.given.join('; ');goalNode.textContent=exercise.prove;body.replaceChildren(...exercise.rows.map(([answer],index)=>{const row=document.createElement('tr');const number=document.createElement('td');number.textContent=String(index+1);const statementCell=document.createElement('td');const statement=document.createElement('input');statement.setAttribute('aria-label',`Statement for proof step ${index+1}`);statement.dataset.proofStatement='';statement.placeholder='Choose the justified statement';const reasonCell=document.createElement('td');const reason=document.createElement('select');reason.setAttribute('aria-label',`Reason for proof step ${index+1}`);reason.dataset.proofReason='';const blank=document.createElement('option');blank.value='';blank.textContent='Choose a reason';reason.append(blank);reasons.forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;reason.append(option);});statementCell.append(statement);reasonCell.append(reason);row.append(number,statementCell,reasonCell);return row;}));section.querySelectorAll('[data-proof-statement]').forEach((input,index)=>{input.value='';input.placeholder=index===0?`Start from a given (${exercise.rows[index][0]})`:'Enter the next justified statement';});status.className='feedback neutral';status.textContent=`Complete ${exercise.rows.length} proof steps. The givens and goal are provided.`;};
    exerciseSelect.addEventListener('change',redraw);section.querySelector('#proofReset').addEventListener('click',redraw);section.querySelector('#proofHint').addEventListener('click',()=>{status.className='feedback neutral';status.textContent=exercises[Number(exerciseSelect.value)].hint;});
    section.querySelector('#proofCheck').addEventListener('click',()=>{const expected=exercises[Number(exerciseSelect.value)].rows;const statements=[...body.querySelectorAll('[data-proof-statement]')];const rowReasons=[...body.querySelectorAll('[data-proof-reason]')];const normal=value=>normalizeAnswer(value);const missing=statements.some(input=>!input.value.trim())||rowReasons.some(select=>!select.value);if(missing){status.className='feedback bad';status.textContent='Complete every statement and choose a reason for every row.';return;}const correct=statements.every((input,index)=>normal(input.value)===normal(expected[index][0])&&rowReasons[index].value===expected[index][1]);status.className=`feedback ${correct?'good':'bad'}`;status.textContent=correct?'Correct proof. Every statement and reason matches a valid step.':'Not quite yet. Check the statements, reasons, and order. Use Hint for a clue or Show one solution to review the completed proof.';});
    section.querySelector('#proofShow').addEventListener('click',()=>{const exercise=exercises[Number(exerciseSelect.value)];body.querySelectorAll('[data-proof-statement]').forEach((input,index)=>input.value=exercise.rows[index][0]);body.querySelectorAll('[data-proof-reason]').forEach((select,index)=>select.value=exercise.rows[index][1]);status.className='feedback neutral';status.textContent='Solution shown. Reset proof to try this exercise again.';});redraw();
  }

  document.addEventListener('DOMContentLoaded', () => setTimeout(() => {
    const app = window.SpanishPracticeApp; if (!app) return; window.VertexApp = app; labels(); app.updateDocumentTitle = () => { document.title = 'Vertex — Accelerated Geometry'; }; const savedPreferences = readPreferences(); if (savedPreferences.modules) app.state.geometryModules = savedPreferences.modules; app.setLevel('geometry',{ historyMode:'replace' }); labels();
    app.getEnabledModules = () => enabledKeys(app).filter((key) => app.state?.geometryModules?.[key] === true && QUESTIONS[key]?.length);
    app.isModulePracticeEnabled = (key) => app.getEnabledModules().includes(key);
    app.getModuleCounts = (key) => ({ total:(QUESTIONS[key] || []).length, available:poolFor(app,key).length });
    app.generateQuestion = (key) => { const pool = poolFor(app,key); if (!pool.length) return null; const item = pool[Math.floor(Math.random() * pool.length)]; return { ...item, module:key, acceptable:item.acceptable instanceof Set ? item.acceptable : answerSet([item.expectedDisplay]) }; };
    app.updateHomeSummary = () => { const node = document.getElementById('homeModuleSummary'); if (node) node.textContent = app.getEnabledModules().map((key) => byKey[key].name).join(', ') || 'No sections selected yet'; };
    app.getSessionTarget = () => app.hasPremiumAccess() ? 18 : 10;
    const originalRefresh = app.refreshSettingsUI.bind(app); app.refreshSettingsUI = (...args) => { const result = originalRefresh(...args); labels(); renderSettings(app); app.updateHomeSummary(); return result; };
    const originalRender = app.renderQuestion.bind(app); app.renderQuestion = (question, options) => { originalRender(question, options); const title = document.getElementById('qaTitle'); if (title) title.textContent = byKey[question?.module]?.name || 'Geometry'; document.getElementById('answerInput')?.setAttribute('placeholder','Type a geometry answer...'); };
    window.VertexMathAnswer = { normalize:normalizeAnswer, answerSet }; installMathKeyboard(); installProofBuilder(); renderSettings(app); app.updateHomeSummary();
    app.runAutomatedChecks = () => { const results = MODULES.map((module) => ({ ok:(QUESTIONS[module.key] || []).length >= 6, label:`${module.name} has a varied question bank` })); results.push({ ok:MODULES.every((module) => module.sources.length > 0), label:'All modules retain PDF source references' }); results.push({ ok:MODULES.every((module) => (QUESTIONS[module.key] || []).some((question) => question.mode === 'mcq')), label:'Every geometry section offers an appropriate multiple-choice check' }); results.push({ ok:normalizeAnswer('  CONGRUENT   ANGLES. ') === 'congruent angles', label:'Answer normalization ignores case, spacing, and punctuation' }); results.push({ ok:normalizeAnswer('x + 2') === normalizeAnswer('x+2'), label:'Math answers accept harmless operator spacing' }); results.push({ ok:normalizeAnswer('-1') !== normalizeAnswer('1'), label:'Math normalization preserves meaningful signs' }); results.push({ ok:normalizeAnswer('√40') === 'sqrt 40' && normalizeAnswer('90°') === '90 degree', label:'Math notation normalization is installed' }); results.push({ ok:document.getElementById('proofBuilder')?.querySelectorAll('#proofExercise option').length >= 6 && document.getElementById('proofBuilder')?.querySelector('[data-proof-statement]'), label:'Guided proof exercises include given, prove, statements, and reasons' }); const output = document.getElementById('checksOutput'); if (output) { const passed = results.filter((item) => item.ok).length; output.className = `feedback ${passed === results.length ? 'good' : 'bad'}`; output.innerHTML = `${results.map((item) => `${item.ok ? '✓' : '✗'} ${item.label}`).join('<br>')}<br><small>Summary: ${passed}/${results.length} passed</small>`; } return { pass:results.filter((item) => item.ok).length, total:results.length, results }; };
    app.refreshSettingsUI();
  }, 0));
})();
