/* Vertex Geometry curriculum adapter. Source: scanned classroom PDFs in ../Canvas Geometry PDFs. */
(() => {
  'use strict';
  window.LearningAppShared?.registerUpdate({id:'vertex-theorem-review-modes-20260927-2',app:'vertex',title:'Get ready for Monday or Tuesday tests: theorem practice',copy:'Review theorem, postulate, definition, and property names in the Geometry reference module. Start with Easy multiple choice, then switch to Hard typing when you’re ready.',action:'vertex-theorems'});
  window.LearningAppShared?.registerUpdate({id:'vertex-test2-review-scratchpaper-20260927',app:'vertex',title:'Test 2 practice from your Canvas review',copy:'Get ready for the Chapter 3 test with scratch-paper-first practice based on the Canvas review: line equations, distance, angle pairs, and proof reasoning. Solve each problem on paper, then choose your answer.',action:'vertex-test2-review'});

  const MODULES = [
    { key:'geometry-1-1', unit:'unit-1', section:'1.1', name:'Points, Lines, and Planes', sources:['01-01_points-lines-planes_annotated.pdf'], premium:false },
    { key:'geometry-1-3', unit:'unit-1', section:'1.3', name:'Midpoint and Distance Formula', sources:['01-03_midpoint-and-distance-formula_annotated.pdf'], premium:false },
    { key:'geometry-1-5', unit:'unit-1', section:'1.5', name:'Measuring and Constructing Angles', sources:['01-05_measuring-angles_annotated.pdf','01-05_more-measuring-angles_annotated.pdf'], premium:false },
    { key:'geometry-1-6', unit:'unit-1', section:'1.6', name:'Pairs of Angles', sources:['01-06_pairs-of-angles_annotated.pdf'], premium:false },
    { key:'geometry-review', unit:'unit-1', section:'1.99', name:'Test 1 Review', sources:['01-99_review-for-test-1_answers.pdf'], premium:true },
    { key:'geometry-2-2', unit:'unit-2', section:'2.2', name:'Inductive and Deductive Reasoning', sources:['02-02_inductive-and-deductive-reasoning_part-1_annotated.pdf'], premium:false },
    { key:'geometry-2-4', unit:'unit-2', section:'2.4', name:'Algebraic Reasoning', sources:['02-04_algebraic-reasoning_annotated.pdf'], premium:false },
    { key:'geometry-2-5', unit:'unit-2', section:'2.5', name:'Proving Statements about Segments and Angles', sources:['02-05_proving-segments-and-angles_annotated.pdf'], premium:false },
    { key:'geometry-2-6', unit:'unit-2', section:'2.6', name:'Proving Geometric Relationships', sources:['02-06_proving-geometric-relationships_annotated.pdf'], premium:false },
    { key:'geometry-3-1', unit:'unit-3', section:'3.1', name:'Pairs of Lines and Angles', sources:['03-01_pairs-of-lines-and-angles_blank.pdf'], premium:false },
    { key:'geometry-3-2', unit:'unit-3', section:'3.2', name:'Parallel Lines and Transversals', sources:['03-02_parallel-lines-and-transversals_annotated.pdf'], premium:false, reduced:true },
    { key:'geometry-3-3', unit:'unit-3', section:'3.3', name:'Proofs with Parallel Lines', sources:['03-03_proofs-with-parallel-lines_annotated.pdf'], premium:true },
    { key:'geometry-3-4', unit:'unit-3', section:'3.4', name:'Proofs with Perpendicular Lines', sources:['03-04_proofs-with-perpendicular-lines_annotated.pdf'], premium:true },
    { key:'geometry-3-5', unit:'unit-3', section:'3.5', name:'Equations of Parallel and Perpendicular Lines', sources:['3.5 Equations of Parallel and Perpendicular Lines.pdf','3.5 Equations of Parallel and Perpendicular Lines - annotated-1.pdf'], premium:false },
    { key:'geometry-review-2', unit:'unit-3', section:'3.99', name:'Test 2 Review', sources:['03-99_review-for-test-2_answers.pdf'], premium:true },
    { key:'geometry-reference', unit:'reference', section:'Reference', name:'Theorems, Definitions, Postulates & Properties', sources:['00_geometry-sequence_highlighted.pdf','01-01_points-lines-planes_annotated.pdf','01-03_midpoint-and-distance-formula_annotated.pdf','01-05_measuring-angles_annotated.pdf','01-05_more-measuring-angles_annotated.pdf','01-06_pairs-of-angles_annotated.pdf','01-99_review-for-test-1_answers.pdf','02-02_inductive-and-deductive-reasoning_part-1_annotated.pdf','02-04_algebraic-reasoning_annotated.pdf','02-05_proving-segments-and-angles_annotated.pdf','02-06_proving-geometric-relationships_annotated.pdf','03-01_pairs-of-lines-and-angles_blank.pdf','03-02_parallel-lines-and-transversals_annotated.pdf','03-03_proofs-with-parallel-lines_annotated.pdf','03-04_proofs-with-perpendicular-lines_annotated.pdf','03-99_review-for-test-2_answers.pdf'], premium:true }
  ];
  const byKey = Object.fromEntries(MODULES.map((module) => [module.key, module]));

  // Shared, conservative normalization: presentation differences are harmless, but
  // aliases remain explicit so incorrect mathematical answers are not accepted.
  const normalize = (value) => String(value ?? '').normalize('NFKC').toLowerCase()
    .replace(/[∠]/g,'angle ').replace(/[≅≡]/g,' congruent ').replace(/[√]/g,'sqrt ')
    .replace(/[×]/g,' x ').replace(/[÷]/g,' / ').replace(/[≤]/g,' less than or equal to ')
    .replace(/[≥]/g,' greater than or equal to ').replace(/[≠]/g,' not equal to ')
    .replace(/[±]/g,' plus or minus ').replace(/[°]/g,' degree ')
    .replace(/\bdegrees\b/g,'degree').replace(/([a-z])(?=\d)/g,'$1 ').replace(/(?<=\d)(?=[a-z])/g,' ')
    .replace(/(?<!\d)\.(?!\d)/g,' ').replace(/[^a-z0-9.+\-/\s]/g,' ').replace(/\s+/g,' ').trim();
  // Whitespace around arithmetic operators is presentation only; keep the
  // operator itself so +, -, and / still distinguish different answers.
  const normalizeAnswer = (value) => normalize(value).replace(/\b(point|angle|segment|unit|degrees?)\b/g,' $1 ').replace(/\s*([.+\-/])\s*/g,'$1').replace(/\s+/g,' ').trim();
  const answerSet = (answers) => new Set((answers || []).flatMap((answer) => { const value = normalizeAnswer(answer); return value ? [value] : []; }));
  const makeQuestion = (id, prompt, answer, aliases = [], options = {}) => ({
    id, mode:options.mode || 'text', prompt, expectedDisplay:answer,
    acceptable:answerSet([answer, ...aliases]), explanation:options.explanation || 'Use the Geometry definition, postulate, property, or theorem from this section.',
    ...(options.mode === 'mcq' ? { options:options.options, correctIndex:options.options.indexOf(answer) } : {})
  });
  const mcq = (id, prompt, answer, options, explanation) => makeQuestion(id, prompt, answer, [], { mode:'mcq', options, explanation });
  const text = (answer) => String(answer);
  const QUESTIONS = {
    'geometry-1-1': [
      mcq('u1-1-point','What undefined term names an exact location?','point',['point','line','plane','ray']), mcq('u1-1-line','What undefined term extends forever in two opposite directions?','line',['point','line','plane','ray']), mcq('u1-1-plane','What undefined term is a flat surface with two dimensions?','plane',['point','line','plane','angle']), mcq('u1-1-segment','A part of a line with two endpoints is a?','line segment',['line segment','ray','plane','angle']), mcq('u1-1-ray','A part of a line with one endpoint that extends forever in one direction is a?','ray',['line','ray','segment','plane']), mcq('u1-1-collinear','Points on the same line are called?','collinear points',['collinear points','coplanar points','opposite rays','skew lines']), makeQuestion('u1-1-coplanar','Points that lie in the same plane are called?','coplanar points',['coplanar','points in the same plane']), mcq('u1-1-opposite-rays','Two opposite rays with a common endpoint form a?','line',['line','segment','angle','plane']), mcq('u1-1-line-notation','Through two distinct points, there is exactly one ___.','line',['line','plane','ray','angle']), makeQuestion('u1-1-ray-order','For ray notation AB, what does the first letter A identify?','endpoint',['the endpoint','starting point','initial point','the starting point'])
    ],
    'geometry-1-3': [
      mcq('u1-3-midpoint','What formula finds the midpoint of A(x₁,y₁) and B(x₂,y₂)?','( (x₁+x₂)/2, (y₁+y₂)/2 )',['( (x₁+x₂)/2, (y₁+y₂)/2 )','(x₁+x₂, y₁+y₂)','(x₂-x₁, y₂-y₁)','√((x₂-x₁)²+(y₂-y₁)²)']), makeQuestion('u1-3-midpoint-numeric','What is the midpoint of J(-3,2) and K(9,2)?','(3,2)',['3, 2','(3, 2)']), makeQuestion('u1-3-other-endpoint','If M(-2,5) is the midpoint and H(-3,7) is one endpoint, what is the other endpoint?','(-1,3)',['-1, 3','(-1, 3)']), mcq('u1-3-distance','Which formula finds the distance between two coordinate points?','distance formula',['distance formula','midpoint formula','slope formula','point-slope formula']), mcq('u1-3-pythagorean','Which theorem can also find coordinate distance using horizontal and vertical legs?','Pythagorean Theorem',['Pythagorean Theorem','Angle Addition Postulate','Segment Addition Postulate','Vertical Angle Theorem']), makeQuestion('u1-3-distance-numeric','Find the distance between (2,5) and (4,-1). Give the exact answer.','2√10',['2 sqrt 10','sqrt 40','√40'])
    ],
    'geometry-1-5': [
      mcq('u1-5-acute','An angle measuring 35° is what type?','acute',['acute','right','obtuse','straight']), mcq('u1-5-right','An angle measuring exactly 90° is what type?','right',['acute','right','obtuse','straight']), makeQuestion('u1-5-obtuse','What range describes an obtuse angle?','greater than 90° and less than 180°',['90 to 180 degrees','between 90 and 180 degrees','more than 90 degrees and less than 180 degrees']), makeQuestion('u1-5-straight','A straight angle always measures?','180°',['180','180 degrees']), makeQuestion('u1-5-addition','If D is inside ∠ABC, what postulate gives m∠ABD + m∠DBC = m∠ABC?','Angle Addition Postulate',['Angle Addition']), makeQuestion('u1-5-bisector','If BD bisects ∠ABC, what equality of measures is true?','m∠ABD = m∠DBC',['m angle abd = m angle dbc','m∠DBC = m∠ABD','m angle dbc = m angle abd']), makeQuestion('u1-5-congruent','If BD bisects ∠ABC, what congruence statement is true?','∠ABD ≅ ∠DBC',['angle abd congruent angle dbc','∠DBC ≅ ∠ABD','angle dbc congruent angle abd']), mcq('u1-5-angle-parts','In ∠ABC, which point is the vertex and which rays are its sides?','Vertex B; rays BA and BC',['Vertex B; rays BA and BC','Vertex A; rays AB and AC','Vertex C; rays CB and CA','Vertex B; rays AB and AC']), makeQuestion('u1-5-bisector-value','BD bisects ∠ABC. If m∠ABD = 4x+2 and m∠DBC = 3x+7, what is x?','5',['x = 5'])
    ],
    'geometry-1-6': [
      mcq('u1-6-vertical','Which angle relationship is always congruent?','vertical angles',['vertical angles','linear pairs','complementary angles','adjacent angles']), makeQuestion('u1-6-adjacent','Adjacent angles share a vertex and a common ___.','side',['common side','ray','common ray']), makeQuestion('u1-6-complementary','Complementary angles have measures that add to?','90°',['90','90 degrees']), makeQuestion('u1-6-supplementary','Supplementary angles have measures that add to?','180°',['180','180 degrees']), makeQuestion('u1-6-linear','Adjacent angles that form a line are a?','linear pair',['a linear pair','linear pair']), makeQuestion('u1-6-linear-properties','A linear pair is adjacent and its angles are what?','supplementary',['supplementary angles']), makeQuestion('u1-6-complement-example','If one complementary angle is 60°, what is the other?','30°',['30','30 degrees']), makeQuestion('u1-6-supplement-example','If one supplementary angle is 150°, what is the other?','30°',['30','30 degrees'])
    ],
    'geometry-review': [mcq('review-midpoint-mcq','A point that divides a segment into two congruent segments is its?','midpoint',['midpoint','angle bisector','transversal','endpoint']), mcq('review-collinear','Points A, B, and C lie on the same line. What term describes these points?','collinear',['collinear','coplanar','parallel','congruent']), makeQuestion('review-distance','What is the distance between (5,6) and (1,3)?','5 units',['5','5 unit']), mcq('review-angle-names','Rays QP, QR, and QS share endpoint Q, with QR between QP and QS. Which list names the two smaller angles and the whole angle?','∠PQR, ∠RQS, and ∠PQS',['∠PQR, ∠RQS, and ∠PQS','∠PQS, ∠RQS, and ∠PQR','∠PQR, ∠PQS, and ∠RQS','∠QPR, ∠QRS, and ∠QPS']), makeQuestion('review-linear','What postulate describes adjacent angles that form a line?','Linear Pair Postulate',['Linear Pair']), makeQuestion('review-supplement','If m∠WXY = (6x+59)° and m∠YXZ = (3x-14)° are supplementary, what is x?','15',['x = 15'])],
    'geometry-2-2': [mcq('u2-2-conjecture-mcq','An unproven statement based on observations is a?','conjecture',['conjecture','theorem','counterexample','postulate']), makeQuestion('u2-2-counterexample','What is an example that disproves a conjecture called?','counterexample',['a counterexample']), makeQuestion('u2-2-inductive','What kind of reasoning uses patterns or examples to form a conjecture?','inductive reasoning',['inductive','reasoning from patterns']), makeQuestion('u2-2-deductive','What kind of reasoning uses facts, definitions, postulates, and theorems?','deductive reasoning',['deductive','reasoning from established facts']), makeQuestion('u2-2-false','To disprove a universal conjecture, how many counterexamples are needed?','one',['1','one counterexample','a single counterexample']), mcq('u2-2-product','A conjecture says the product of any three negative integers is negative. Is it true or false?','true',['true','false'])],
    'geometry-2-4': [mcq('u2-4-segment','If B is between A and C, AB + BC = AC is the?','Segment Addition Postulate',['Segment Addition Postulate','Angle Addition Postulate','Substitution Property','Linear Pair Postulate']), mcq('u2-4-angle','Adjacent angle measures add to the whole angle by the?','Angle Addition Postulate',['Segment Addition Postulate','Angle Addition Postulate','Vertical Angle Theorem','Linear Pair Postulate']), mcq('u2-4-addition','If a=b, then a+c=b+c uses which property?','Addition Property of Equality',['Addition Property of Equality','Subtraction Property of Equality','Reflexive Property','Substitution Property']), makeQuestion('u2-4-subtraction','If a=b, then a-c=b-c uses which property?','Subtraction Property of Equality',['Subtraction Property']), makeQuestion('u2-4-multiplication','If a=b, then ac=bc uses which property?','Multiplication Property of Equality',['Multiplication Property']), makeQuestion('u2-4-division','If a=b and c≠0, then a/c=b/c uses which property?','Division Property of Equality',['Division Property']), makeQuestion('u2-4-substitution','What property permits replacing equal values in an equation?','Substitution Property of Equality',['Substitution Property']), makeQuestion('u2-4-reflexive','What property states a quantity is equal to itself?','Reflexive Property of Equality',['Reflexive Property']), makeQuestion('u2-4-symmetric','If a=b, then b=a uses which property?','Symmetric Property of Equality',['Symmetric Property']), makeQuestion('u2-4-transitive','If a=b and b=c, then a=c uses which property?','Transitive Property of Equality',['Transitive Property']), makeQuestion('u2-4-distributive','What property expands a(b+c) into ab+ac?','Distributive Property',['Distributive']), makeQuestion('u2-4-proof-columns','What are the two columns in a 2-Column Proof?','statements and reasons',['statement and reason','statements and reason'])],
    'geometry-2-5': [mcq('u2-5-reflexive','If AB ≅ AB, which property of congruence is shown?','Reflexive Property of Congruence',['Reflexive Property of Congruence','Symmetric Property of Congruence','Transitive Property of Congruence','Definition of Congruent Segments']), makeQuestion('u2-5-symmetric','If AB ≅ CD, then CD ≅ AB. Name the property.','Symmetric Property of Congruence',['Symmetric Property']), makeQuestion('u2-5-transitive','If AB ≅ CD and CD ≅ RT, then AB ≅ RT. Name the property.','Transitive Property of Congruence',['Transitive Property']), makeQuestion('u2-5-definition-segments','If AB ≅ CD, then AB = CD. Name the reason.','Definition of Congruent Segments',['Definition of Congruent Segment Lengths']), makeQuestion('u2-5-definition-angles','If ∠A ≅ ∠B, then m∠A = m∠B. Name the reason.','Definition of Congruent Angles',['Definition of Congruent Angle Measures']), mcq('u2-5-bisector','A segment bisector divides a segment into two what segments?','congruent segments',['congruent segments','parallel segments','adjacent angles','supplementary angles']), makeQuestion('u2-5-proof-given','In a proof, information supplied in the problem is called the?','given',['a given'])],
    'geometry-2-6': [mcq('u2-6-vertical-mcq','Which theorem proves vertical angles are congruent?','Vertical Angle Theorem',['Vertical Angle Theorem','Linear Pair Postulate','Congruent Supplements Theorem','Angle Addition Postulate']), makeQuestion('u2-6-supplements','What theorem says angles supplementary to the same angle are congruent?','Congruent Supplements Theorem',['Congruent Supplements']), makeQuestion('u2-6-complements','What theorem says angles complementary to the same angle are congruent?','Congruent Complements Theorem',['Congruent Complements']), makeQuestion('u2-6-linear-pair','What postulate says angles in a linear pair are supplementary?','Linear Pair Postulate',['Linear Pair']), makeQuestion('u2-6-transitive','Which property can connect ∠1 ≅ ∠3 and ∠3 ≅ ∠4 to prove ∠1 ≅ ∠4?','Transitive Property of Congruence',['Transitive Property']), makeQuestion('u2-6-proof-reason','In a two-column proof, definitions, postulates, theorems, and properties belong in the?','reasons column',['reason column'])],
    'geometry-3-1': [mcq('u3-1-parallel','Lines in the same plane that never intersect are?','parallel lines',['parallel lines','perpendicular lines','skew lines','transversal']), makeQuestion('u3-1-perpendicular','Lines that intersect to form right angles are?','perpendicular lines',['perpendicular']), makeQuestion('u3-1-skew','Lines that do not intersect and are not coplanar are?','skew lines',['skew']), makeQuestion('u3-1-transversal','A line that intersects two or more coplanar lines is a?','transversal',['a transversal']), makeQuestion('u3-1-intersecting-planes','Two planes that meet intersect in a?','line',['line of intersection']), makeQuestion('u3-1-nonparallel','When a transversal crosses two non-parallel lines, corresponding angles are not guaranteed to be what?','congruent',['equal'])],
    'geometry-3-2': [mcq('u3-2-alternate-interior','When parallel lines are cut by a transversal, alternate interior angles are?','congruent',['congruent','supplementary','complementary','vertical']), makeQuestion('u3-2-alternate-exterior','When parallel lines are cut by a transversal, alternate exterior angles are?','congruent',['congruent angles','equal']), makeQuestion('u3-2-corresponding','When parallel lines are cut by a transversal, corresponding angles are?','congruent',['congruent angles','equal']), makeQuestion('u3-2-consecutive-interior','When parallel lines are cut by a transversal, consecutive interior (same-side interior) angles are?','supplementary',['supplementary angles','add to 180 degrees']), makeQuestion('u3-2-consecutive-exterior','When parallel lines are cut by a transversal, consecutive exterior (same-side exterior) angles are?','supplementary',['supplementary angles','add to 180 degrees']), makeQuestion('u3-2-equation','Two adjacent angles form a linear pair and measure 120° and x°. What is x?','60',['x = 60']), makeQuestion('u3-2-corresponding-equation','When parallel lines are cut by a transversal, corresponding angles measure 120° and (3y+6)°. What is y?','38',['y = 38']), makeQuestion('u3-2-proof','Given k ∥ n, which theorem proves a pair of alternate interior angles congruent?','Alternate Interior Angles Theorem')],
    'geometry-3-3': [mcq('u3-3-converse-mcq','For two lines cut by a transversal, if corresponding angles are congruent, what can be concluded?','The lines are parallel',['The lines are parallel','The lines are perpendicular','The lines intersect at a right angle','The lines are skew']), makeQuestion('u3-3-transitive-parallel','If a ∥ b and b ∥ c, then a ∥ c. Name the theorem.','Transitive Property of Parallel Lines Theorem',['Transitive Property of Parallel Lines']), makeQuestion('u3-3-alt-interior-converse','For two lines cut by a transversal, if alternate interior angles are congruent, then the lines are?','parallel',['parallel lines']), makeQuestion('u3-3-alt-exterior-converse','For two lines cut by a transversal, if alternate exterior angles are congruent, then the lines are?','parallel',['parallel lines']), makeQuestion('u3-3-consecutive-interior-converse','For two lines cut by a transversal, if consecutive interior angles are supplementary, then the lines are?','parallel',['parallel lines']), makeQuestion('u3-3-consecutive-exterior-converse','For two lines cut by a transversal, if consecutive exterior angles are supplementary, then the lines are?','parallel',['parallel lines']), makeQuestion('u3-3-proof-reason','Given congruent corresponding angles formed by two lines and a transversal, which converse theorem proves the lines parallel?','Corresponding Angles Converse Theorem',['Corresponding Angles Converse']), makeQuestion('u3-3-equation','What value of x makes lines m and n parallel if (4(x+5))° and 72° are consecutive exterior angles?','22',['x = 22'])],
    'geometry-3-4': [mcq('u3-4-shortest-distance-mcq','The shortest distance from a point to a line is measured along a?','perpendicular segment',['perpendicular segment','parallel segment','angle bisector','transversal']), makeQuestion('u3-4-distance-formula','To find the length of the perpendicular from a point to a line, use the?','distance formula',['distance formula']), makeQuestion('u3-4-bisector','A perpendicular bisector passes through the segment midpoint at what angle?','a right angle',['90 degrees','90°','90']), makeQuestion('u3-4-parallel-perpendicular','In a plane, if a transversal is perpendicular to one of two parallel lines, then it is perpendicular to the?','other line'), makeQuestion('u3-4-same-line','In the same plane, if two lines are perpendicular to the same line, then they are?','parallel'), makeQuestion('u3-4-four-right-angles','Two intersecting perpendicular lines form how many right angles?','four',['4']), makeQuestion('u3-4-definition','A line that passes through a segment midpoint at a right angle is its?','perpendicular bisector',['perpendicular bisector line'])],
    'geometry-3-5': [mcq('line35-parallel-slope-mcq','What slope must a line have to be parallel to y = 5x + 3?','5',['5','-5','1/5','-1/5']), mcq('line35-parallel-point','Which equation describes the line through (4, 6) parallel to y = 5x + 3?','y = 5x - 14',['y = 5x - 14','y = 5x + 14','y = -5x + 26','y = 1/5x + 26/5']), makeQuestion('line35-perpendicular-slope','What is the slope of a line perpendicular to a line with slope -1/12?','12'), mcq('line35-perpendicular-point','Which equation describes the line through (2, -3) perpendicular to y = -6x + 10?','y = 1/6x - 10/3',['y = 1/6x - 10/3','y = -6x + 9','y = 6x - 15','y = 1/6x + 10/3']), mcq('line35-vertical','What is the equation of the vertical line through (3, -2)?','x = 3',['x = 3','y = 3','x = -2','y = -2']), mcq('line35-horizontal','What is the equation of the horizontal line through (4, 6)?','y = 6',['y = 6','x = 6','y = 4','x = 4']), makeQuestion('line35-parallel-compare','How do the slopes of distinct parallel nonvertical lines compare?','They are equal.',['they have the same slope']), makeQuestion('line35-perpendicular-compare','How do the slopes of perpendicular nonvertical lines compare?','They are negative reciprocals.',['their slopes are negative reciprocals','the product of their slopes is -1'])],
    'geometry-review-2': [
      mcq('review2-perpendicular-slope-mcq','The line y = -x/12 + 8 is perpendicular to a new line. What is the new line’s slope?','12',['12','-12','1/12','-1/12'],'Perpendicular nonvertical slopes are negative reciprocals. The negative reciprocal of -1/12 is 12.'),
      mcq('review2-perpendicular-equation','Which line passes through (8, 5) and is perpendicular to y = -x/12 + 8?','y = 12x - 91',['y = 12x - 91','y = -12x + 101','y = x/12 + 4 1/3','y = -x/12 + 5 2/3'],'Use perpendicular slope 12, then substitute (8, 5): 5 = 12(8) + b, so b = -91.'),
      mcq('review2-bisector-midpoint','What is the midpoint of P(4, -8) and Q(8, 8)?','(6, 0)',['(6, 0)','(4, 0)','(6, 8)','(2, 16)'],'Average the x-coordinates and y-coordinates separately: ((4+8)/2, (-8+8)/2) = (6, 0).'),
      mcq('review2-bisector-slope','A segment has endpoints P(4, -8) and Q(8, 8). What slope should its perpendicular bisector have?','-1/4',['-1/4','4','1/4','-4'],'The segment slope is (8 - (-8))/(8 - 4) = 4. Its perpendicular slope is -1/4.'),
      mcq('review2-bisector-equation','Which is the perpendicular bisector of the segment joining P(4, -8) and Q(8, 8)?','y = -x/4 + 3/2',['y = -x/4 + 3/2','y = 4x - 24','y = -x/4 + 6','y = x/4 + 3/2'],'The midpoint is (6, 0) and the perpendicular slope is -1/4. Substitution gives b = 3/2.'),
      mcq('review2-parallel-equation','Which equation describes the line through (4, 6) parallel to y = 5x + 3?','y = 5x - 14',['y = 5x - 14','y = 5x + 14','y = -5x + 26','y = x/5 + 26/5'],'Parallel lines have the same slope. With slope 5 through (4, 6), b = 6 - 20 = -14.'),
      mcq('review2-point-parallel','Which equation describes the line through (2, -3) parallel to y = -6x + 10?','y = -6x + 9',['y = -6x + 9','y = -6x - 9','y = 6x - 15','y = x/6 - 10/3'],'Keep slope -6. Substituting (2, -3) gives -3 = -12 + b, so b = 9.'),
      mcq('review2-parallel-variation','Which line passes through (8, 5) and is parallel to y = -x/12 + 8?','y = -x/12 + 17/3',['y = -x/12 + 17/3','y = 12x - 91','y = x/12 + 13/3','y = -12x + 101'],'Parallel lines keep slope -1/12. Substituting (8, 5) gives b = 5 + 2/3 = 17/3.'),
      mcq('review2-distance-line','What is the exact distance from Q(-10, -4) to the line 5x - y = 6?','2√26',['2√26','2√13','26/5','52'],'Write 5x - y - 6 = 0. The point-to-line distance is |-50 + 4 - 6|/√(25+1) = 52/√26 = 2√26.'),
      mcq('review2-distance-segment-line','What is the distance from P(5, -2) to line AB when A(-3, -2) and B(1, 2)?','4√2',['4√2','√32','4','8'],'AB has slope 1 and equation y = x + 1. The perpendicular distance from (5, -2) is |5 - (-2) + 1|/√2 = 4√2.'),
      mcq('review2-distance-variation','What is the distance from (0, 2) to the line 3x + 4y - 9 = 0?','1/5',['1/5','1','5','2/5'],'Use |3(0) + 4(2) - 9|/√(3²+4²) = 1/5.'),
      mcq('review2-parallel-from-standard','A line is parallel to 4x + 2y = 5 and passes through (6, 4). Which equation is it?','y = -2x + 16',['y = -2x + 16','y = x/2 + 1','y = 2x - 8','y = -2x - 8'],'Rewrite the given line as y = -2x + 5/2. Keep slope -2; through (6, 4), the new intercept is 16.'),
      mcq('review2-perpendicular-from-point','Which line passes through (-2, 3) and is perpendicular to y = 4x - 1?','y = -x/4 + 5/2',['y = -x/4 + 5/2','y = 4x + 11','y = x/4 + 7/2','y = -4x - 5'],'The perpendicular slope is -1/4. Substitution gives 3 = 1/2 + b, so b = 5/2.'),
      mcq('review2-perpendicular-trap','A line is perpendicular to a line with slope 3. What is its slope?','-1/3',['-1/3','-3','1/3','3'],'The negative reciprocal is -1/3. Negating the slope without taking its reciprocal is a common mistake.'),
      mcq('review2-corresponding-equation','Parallel lines are cut by a transversal. Corresponding angles measure (3x + 12)° and (5x - 20)°. What is x?','16',['16','4','28','52'],'Corresponding angles are congruent: 3x + 12 = 5x - 20, so x = 16.'),
      mcq('review2-same-side-equation','Parallel lines are cut by a transversal. Same-side interior angles are (4x + 8)° and (2x + 28)°. What is x?','24',['24','36','20','16'],'Same-side interior angles are supplementary: (4x + 8) + (2x + 28) = 180, so x = 24.'),
      mcq('review2-q9-corresponding-1-17','In the Canvas review diagram, ∠1 and ∠17 are corresponding angles. If ∠1 = 118° and the lines are parallel, what is ∠17?','118°',['118°','62°','90°','180°'],'Corresponding angles are congruent when the lines are parallel.'),
      mcq('review2-q9-corresponding-13-5','In the Canvas review diagram, ∠13 and ∠5 are corresponding angles. If ∠13 = 73°, what is ∠5?','73°',['73°','107°','117°','180°'],'Corresponding angles have equal measures when the lines are parallel.'),
      mcq('review2-q9-consecutive-14-8','In the Canvas review diagram, ∠14 and ∠8 are consecutive interior angles. If ∠14 = 63°, what is ∠8?','117°',['117°','63°','27°','153°'],'Consecutive interior angles are supplementary: 180° - 63° = 117°.'),
      mcq('review2-q9-consecutive-4-18','In the Canvas review diagram, ∠4 and ∠18 are consecutive interior angles. If ∠4 = 104°, what is ∠18?','76°',['76°','104°','14°','284°'],'Consecutive interior angles add to 180°, so 180° - 104° = 76°.'),
      mcq('review2-q9-alternate-interior-7-11','In the Canvas review diagram, ∠7 and ∠11 are alternate interior angles. If ∠7 = 102°, what is ∠11?','102°',['102°','78°','180°','51°'],'Alternate interior angles are congruent when the lines are parallel.'),
      mcq('review2-q9-alternate-interior-17-4','In the Canvas review diagram, ∠17 and ∠4 are alternate interior angles. If ∠17 = 49°, what is ∠4?','49°',['49°','131°','41°','180°'],'Alternate interior angles are congruent when the lines are parallel.'),
      mcq('review2-q9-alternate-exterior-6-15','In the Canvas review diagram, ∠6 and ∠15 are alternate exterior angles. If ∠6 = 46°, what is ∠15?','46°',['46°','134°','90°','224°'],'Alternate exterior angles are congruent when the lines are parallel.'),
      mcq('review2-q9-alternate-exterior-18-15','In the Canvas review diagram, ∠18 and ∠15 are alternate exterior angles. If ∠18 = 129°, what is ∠15?','129°',['129°','51°','90°','231°'],'Alternate exterior angles are congruent when the lines are parallel.'),
      mcq('review2-corresponding-converse','Two lines are cut by a transversal. A pair of corresponding angles is congruent. Which conclusion is justified?','The two lines are parallel.',['The two lines are parallel.','The two lines are perpendicular.','The two angles are supplementary.','There is not enough information.'],'The Corresponding Angles Converse proves the lines are parallel.'),
      mcq('review2-proof-corresponding-reason','In the Canvas proof, ℓ ∥ m. Which reason justifies ∠5 ≅ ∠7 when those angles are corresponding?','Corresponding Angles Theorem',['Corresponding Angles Theorem','Alternate Interior Angles Converse','Vertical Angles Theorem','Linear Pair Postulate'],'Parallel lines make corresponding angles congruent by the Corresponding Angles Theorem.'),
      mcq('review2-proof-transitive','The proof gives ∠5 ≅ ∠4 and establishes ∠5 ≅ ∠7. Which property lets us conclude ∠4 ≅ ∠7?','Transitive Property of Congruence',['Transitive Property of Congruence','Corresponding Angles Converse','Substitution Property of Equality','Reflexive Property of Congruence'],'If two angles are congruent to the same angle, they are congruent to each other.'),
      mcq('review2-proof-converse','In the Canvas proof, ∠4 and ∠7 are alternate interior angles for lines a and b. If ∠4 ≅ ∠7, which reason proves a ∥ b?','Alternate Interior Angles Converse',['Alternate Interior Angles Converse','Alternate Interior Angles Theorem','Corresponding Angles Theorem','Transitive Property of Parallel Lines'],'The converse uses congruent alternate interior angles to prove the two lines parallel.'),
      mcq('review2-proof-trap','Two vertical angles are congruent. Does that fact alone prove that two different lines are parallel?','No; vertical angles are congruent regardless of whether the lines are parallel.',['No; vertical angles are congruent regardless of whether the lines are parallel.','Yes; use the Corresponding Angles Converse.','Yes; every congruent angle pair proves parallel lines.','No; vertical angles must be supplementary.'],'The converse theorems require a transversal creating corresponding, alternate interior/exterior, or same-side angle pairs.'),
      mcq('review2-perpendicular-foot','For a point-to-line distance problem, which segment gives the shortest distance from the point to the line?','A perpendicular segment from the point to the line.',['A perpendicular segment from the point to the line.','Any segment parallel to the line.','A segment joining the point to any endpoint.','A segment that bisects the nearest angle.'],'The shortest distance from a point to a line is measured along the perpendicular.')
    ],
    'geometry-reference': [mcq('ref-point-mcq','An exact location with no size or dimension is a?','point',['point','line','plane','ray']), mcq('ref-line-mcq','A set of points extending forever in two directions is a?','line',['point','line','segment','plane']), makeQuestion('ref-plane','A flat surface with no thickness extending in two dimensions is a?','plane'), makeQuestion('ref-conjecture','An unproven statement based on observations is a?','conjecture',['an unproven statement']), makeQuestion('ref-counterexample','An example that disproves a conjecture is a?','counterexample'), makeQuestion('ref-segment-addition','AB + BC = AC when B is between A and C is the?','Segment Addition Postulate'), makeQuestion('ref-angle-addition','m∠ABD + m∠DBC = m∠ABC is the?','Angle Addition Postulate'), makeQuestion('ref-vertical','Vertical angles are congruent by the?','Vertical Angle Theorem'), makeQuestion('ref-linear-pair','A linear pair is supplementary by the?','Linear Pair Postulate'), makeQuestion('ref-congruent-supplements','Angles supplementary to the same angle are congruent by the?','Congruent Supplements Theorem'), makeQuestion('ref-congruent-complements','Angles complementary to the same angle are congruent by the?','Congruent Complements Theorem'), makeQuestion('ref-definition-congruent','Congruent segments have equal lengths by the?','Definition of Congruent Segments'), makeQuestion('ref-reflexive','A quantity equal to itself uses the?','Reflexive Property of Equality'), makeQuestion('ref-symmetric','If a=b then b=a uses the?','Symmetric Property of Equality'), makeQuestion('ref-transitive','If a=b and b=c then a=c uses the?','Transitive Property of Equality'), makeQuestion('ref-distributive','a(b+c)=ab+ac is the?','Distributive Property'), makeQuestion('ref-parallel','Lines that never intersect in a plane are?','parallel lines',['parallel']), makeQuestion('ref-perpendicular','Lines that form right angles are?','perpendicular lines',['perpendicular']), makeQuestion('ref-transversal','A line intersecting two or more coplanar lines is a?','transversal',['a transversal']), makeQuestion('ref-corresponding','For parallel lines cut by a transversal, corresponding angles are?','congruent',['equal']), makeQuestion('ref-same-side','For parallel lines cut by a transversal, same-side interior angles are?','supplementary',['supplementary angles']), makeQuestion('ref-converse','The converse of a parallel-lines angle theorem is used to prove the lines are?','parallel',['parallel lines'])]
  };

  const THEOREM_ALIASES = {
    'segment addition postulate':['segment addition','segment addition post.','sap'], 'angle addition postulate':['angle addition','angle addition post.','aap'],
    'vertical angle theorem':['vertical angles theorem','vertical angle thm.','vat'], 'linear pair postulate':['linear pair','linear pair post.','lpp'],
    'congruent supplements theorem':['congruent supplements','congruent supplements thm.','cst'], 'congruent complements theorem':['congruent complements','congruent complements thm.','cct'],
    'definition of congruent segments':['congruent segments definition','def. of congruent segments','dcs'], 'reflexive property of equality':['reflexive property','reflexive property of eq.','rpe'],
    'symmetric property of equality':['symmetric property','symmetric property of eq.','spe'], 'transitive property of equality':['transitive property','transitive property of eq.','tpe'],
    'distributive property':['distributive property of equality','distributive prop.','dp'], 'alternate interior angles theorem':['alternate interior angles','alternate interior angle theorem','aiat'],
    'corresponding angles theorem':['corresponding angles','corresponding angles thm.','cat'], 'transitive property of parallel lines theorem':['transitive property of parallel lines','transitive parallel lines theorem','tpplt'],
    'corresponding angles converse theorem':['corresponding angles converse','corresponding angles converse thm.','cac']
  };
  const canonicalName = (value) => normalizeAnswer(value).replace(/\./g,'').replace(/\b(def|thm|post)\b/g,(token) => ({def:'definition',thm:'theorem',post:'postulate'})[token]).replace(/\s+/g,' ').trim();
  const theoremQuestion = (source, allFacts, mode) => {
    const answer = String(source.expectedDisplay || '').trim(), canonical = canonicalName(answer);
    const distractors = [...new Set(allFacts.map((item) => String(item.expectedDisplay || '').trim()).filter((name) => name && canonicalName(name) !== canonical))].sort((a,b) => Math.abs(a.length-answer.length)-Math.abs(b.length-answer.length)).slice(0,3);
    const fallback = ['Angle Addition Postulate','Linear Pair Postulate','Vertical Angle Theorem','Reflexive Property of Equality'];
    while (distractors.length < 3) { const next = fallback.find((name) => canonicalName(name) !== canonical && !distractors.some((item) => canonicalName(item) === canonicalName(name))); if (!next) break; distractors.push(next); }
    const options = [answer, ...distractors].sort((a,b) => (a.length % 7) - (b.length % 7) || a.localeCompare(b));
    return { ...source, mode, options:mode === 'mcq' ? options : undefined, correctIndex:mode === 'mcq' ? options.indexOf(answer) : undefined,
      acceptable:new Set([answer, ...(THEOREM_ALIASES[canonical] || [])].map(canonicalName)), theoremDrill:true,
      explanation:`${answer} — identify the rule by its exact condition, not a nearby theorem.` };
  };
  const poolFor = (app, key) => {
    const base = (QUESTIONS[key] || []).filter((item) => !app.state?.hiddenItems?.[item.id]);
    if (key !== 'geometry-reference') return base;
    const mode = readPreferences().theoremMode === 'hard' ? 'text' : 'mcq';
    const facts = base.filter((item) => /Postulate|Theorem|Property|Definition/i.test(item.expectedDisplay || '') && !/parallel lines|perpendicular lines|reasons column/i.test(item.expectedDisplay || ''));
    return [...base.filter((item) => !facts.includes(item)), ...facts.map((item) => theoremQuestion({ ...item, id:`theorem-${item.id}`, mode,
      prompt:`${mode === 'mcq' ? 'Choose' : 'Type the exact name of'} the theorem, postulate, definition, or property that fits: ${item.prompt.replace(/\?$/,'')}${mode === 'mcq' ? '?' : '.'}`
    }, facts, mode))];
  };
  const enabledKeys = (app) => MODULES.filter((module) => !module.premium || app.hasPremiumAccess?.()).map((module) => module.key);
  const PREF_COOKIE = 'vertex_geometry_preferences_v1';
  const readPreferences = () => {
    try { const raw = document.cookie.split('; ').find((part) => part.startsWith(`${PREF_COOKIE}=`)); return raw ? JSON.parse(decodeURIComponent(raw.slice(PREF_COOKIE.length + 1))) : {}; } catch (_) { return {}; }
  };
  const writePreferences = (preferences) => { try { document.cookie = `${PREF_COOKIE}=${encodeURIComponent(JSON.stringify(preferences))}; max-age=31536000; path=/; SameSite=Lax`; } catch (_) {} };

  function installMathKeyboard() {
    const block = document.getElementById('textBlock'); const input = document.getElementById('answerInput');
    if (!block || !input || document.getElementById('vertexMathKeyboard')) return;
    const keyboard = document.createElement('div'); keyboard.id = 'vertexMathKeyboard'; keyboard.className = 'math-keyboard'; keyboard.setAttribute('aria-label','Math symbols');
    const symbols = ['√','π','°','×','÷','≤','≥','≠','±','⁄','x²'];
    keyboard.innerHTML = `<span class="math-keyboard-label">Math symbols</span>${symbols.map((symbol) => `<button type="button" class="btn small" data-math-symbol="${symbol}" aria-label="Insert ${symbol}">${symbol}</button>`).join('')}`;
    block.prepend(keyboard);
    keyboard.addEventListener('click', (event) => { const button = event.target.closest('[data-math-symbol]'); if (!button) return; const symbol = button.dataset.mathSymbol; const start = input.selectionStart ?? input.value.length; const end = input.selectionEnd ?? input.value.length; input.value = `${input.value.slice(0,start)}${symbol}${input.value.slice(end)}`; input.focus(); input.setSelectionRange(start + symbol.length, start + symbol.length); });
    window.VertexMathKeyboard = { insert:(symbol) => keyboard.querySelector(`[data-math-symbol="${symbol}"]`)?.click() };
  }

  function renderSettings(app) {
    const section = document.getElementById('moduleSettingsSection'); if (!section) return;
    const unlocked = !!app.hasPremiumAccess?.(); const preferences = readPreferences(); const saved = app.state?.geometryModules || preferences.modules || {};
    const markup = ['unit-1','unit-2','unit-3','reference'].map((unit) => {
      const label = unit === 'reference' ? 'Theorems, Definitions, Postulates & Properties' : `Unit ${unit.slice(-1)}`;
      const counts = { locked: 0, reduced: 0 };
      const cards = MODULES.filter((module) => module.unit === unit).map((module) => { const locked = module.premium && !unlocked; const kind = locked ? 'locked' : module.reduced ? 'reduced' : ''; const showBadge = kind && counts[kind] < (kind === 'locked' ? 1 : 2); if (showBadge) counts[kind] += 1; const description = locked ? 'Premium only: unlock this geometry section.' : module.reduced ? 'Free includes a smaller rotation; Premium adds the complete section.' : ''; const badge = showBadge ? `<button type="button" class="premium-badge premium-badge-${kind}" data-premium-lock="true" title="${description}" aria-label="${description}">${kind === 'locked' ? '🔒' : '◐'}</button>` : ''; const practiceNote = module.key === 'geometry-review-2' ? '<div class="module-practice-note">📝 Scratch-paper-first practice · Canvas Test 2 review problems · multiple choice with worked feedback</div>' : ''; return `<div class="toggle${locked ? ' module-locked' : ''}${module.key === 'geometry-review-2' ? ' test2-review-module' : ''}"><div><div class="label">${module.section} ${module.name} ${badge}</div><div class="desc">${module.sources.length} source PDF${module.sources.length === 1 ? '' : 's'} · ${QUESTIONS[module.key].length} questions${locked ? ' · Premium' : ''}</div>${practiceNote}</div><label><input type="checkbox" data-geometry-module="${module.key}" aria-label="Toggle ${module.name} module" ${saved[module.key] === true ? 'checked' : ''} ${locked ? 'disabled' : ''}><span class="switch" aria-hidden="true"></span></label></div>`; }).join('');
      return `<details class="module-group"${preferences.groups?.[unit] === true ? ' open' : ''}><summary>${label}</summary><div class="module-group-content">${cards}</div></details>`;
    }).join('');
    section.innerHTML = '<summary class="settings-section-summary">Geometry modules</summary>' + markup;
    const modeTools = document.createElement('div');
    modeTools.className = 'theorem-mode-tools';
    modeTools.innerHTML = `<p class="muted small">Theorem name practice</p><div role="group" aria-label="Theorem practice difficulty"><button type="button" class="btn small" data-theorem-mode="easy">Easy · multiple choice</button><button type="button" class="btn small" data-theorem-mode="hard">Hard · type the name</button></div>`;
    const shareTools = document.createElement('div'); shareTools.className = 'module-share-tools';
    shareTools.innerHTML = '<button type="button" class="btn small" id="shareModulesBtn">🔗 Share selected modules</button><span id="moduleShareStatus" role="status" aria-live="polite"></span>';
    const referenceContent = section.querySelector('[data-geometry-module="geometry-reference"]')?.closest('.toggle')?.firstElementChild;
    if (referenceContent) referenceContent.append(modeTools);
    else section.append(modeTools);
    section.append(shareTools);
    shareTools.querySelector('#shareModulesBtn').addEventListener('click', async () => {
      const selected = [...section.querySelectorAll('[data-geometry-module]:checked:not(:disabled)')].map((input) => input.dataset.geometryModule);
      const query = new URLSearchParams(location.search); query.set('modules', selected.join(','));
      const url = `${location.origin}${location.pathname}?${query}${location.hash}`; history.replaceState(null, '', url);
      try { await navigator.clipboard.writeText(url); shareTools.querySelector('#moduleShareStatus').textContent = 'Link copied.'; }
      catch (_) { window.prompt('Copy this module link:', url); }
    });
    const syncMode = () => modeTools.querySelectorAll('[data-theorem-mode]').forEach((button) => {
      const active = (readPreferences().theoremMode || 'easy') === button.dataset.theoremMode;
      button.classList.toggle('primary', active); button.setAttribute('aria-pressed', String(active));
    });
    modeTools.querySelectorAll('[data-theorem-mode]').forEach((button) => button.addEventListener('click', (event) => {
      event.stopPropagation();
      writePreferences({ ...readPreferences(), theoremMode:button.dataset.theoremMode }); syncMode();
      if (app.currentQuestion?.theoremDrill) { app.answered = false; app.nextQuestion({ keepFeedback:false }); }
    }));
    syncMode();
    section.querySelectorAll('[data-premium-lock]').forEach((button) => button.addEventListener('click', (event) => {
      event.preventDefault(); event.stopPropagation();
      document.querySelector('.shared-prompt-premium')?.remove();
      const settings = document.getElementById('settingsOverlay');
      if (settings) { settings.hidden = true; settings.style.display = 'none'; }
      const premium = document.getElementById('premiumOverlay');
      if (window.openPremiumFromLock) { window.openPremiumFromLock(); return; }
      if (premium) { premium.hidden = false; premium.style.display = 'flex'; premium.style.zIndex = '2147483000'; }
      app.openPremiumAccess?.();
      if (premium) { premium.hidden = false; premium.style.display = 'flex'; premium.style.zIndex = '1400'; }
    }));
    section.querySelectorAll('[data-geometry-module]:not(:disabled)').forEach((box) => box.addEventListener('change', () => { app.state.geometryModules = Object.fromEntries([...section.querySelectorAll('[data-geometry-module]')].map((item) => [item.dataset.geometryModule, item.checked])); writePreferences({ ...readPreferences(), modules: app.state.geometryModules }); app.saveSoon(); app.updateHomeSummary?.(); window.dispatchEvent(new Event('learning-modules-changed')); }));
    section.querySelectorAll('details.module-group').forEach((group) => group.addEventListener('toggle', () => { const summary = group.querySelector('summary').textContent; const groups = { ...readPreferences().groups, [summary.startsWith('Theorems, Definitions') ? 'reference' : `unit-${summary.slice(-1)}`]: group.open }; writePreferences({ ...readPreferences(), groups }); }));
  }

  function labels() {
    document.title = 'Vertex — Accelerated Geometry'; document.documentElement.style.setProperty('--accent','#166534');
    document.querySelectorAll('#brandName, .app-switcher-menu a.is-current span').forEach((node) => { node.textContent = 'Vertex'; });
    ['subtitle','headerLevel','classSwitcherLabel'].forEach((id) => { const node = document.getElementById(id); if (node) node.textContent = 'Accelerated Geometry'; });
    const heading = document.querySelector('#homeCard h1'); if (heading) heading.textContent = 'Practice Accelerated Geometry';
    const lead = document.querySelector('#homeCard .home-intro'); if (lead) lead.textContent = 'Choose sections, then start a focused geometry session.';
    ['.dashboard-switcher','.level-switch','#spanish2Panel','#practiceOnlyRow','#practiceOnlyMobile','#soloSelect','#numbersSection','#numbersGuideOverlay','#summerPrepSettings','#practiceBehaviorSettings','#accentToolbar'].forEach((selector) => document.querySelectorAll(selector).forEach((node) => node.hidden = true));
    const levelPanel = document.getElementById('spanish1Panel'); if (levelPanel) levelPanel.hidden = false;
    const input = document.getElementById('answerInput'); if (input) input.placeholder = 'Type a geometry answer...';
    const enter = document.getElementById('enterPracticeBtn'); if (enter) { enter.innerHTML = 'Enter geometry session <span aria-hidden="true">→</span>'; enter.setAttribute('aria-label','Enter geometry session'); }
    const help = [...document.querySelectorAll('.settings-accordion')].find((node) => /Keyboard\s*&\s*Help/i.test(node.querySelector('summary')?.textContent || '')); if (help) { help.querySelector('summary').innerHTML = 'Geometry keyboard help <span class="summary-note">Optional</span>'; help.querySelector('.small.muted').textContent = 'Use the math symbol keyboard when notation is helpful. Enter submits your answer.'; }
  }

  function installProofBuilder(app) {
    const section = document.createElement('section'); section.className = 'proof-builder card'; section.id = 'proofBuilder'; section.setAttribute('aria-labelledby','proofBuilderTitle');
    section.hidden = true;
    section.innerHTML = `<h2 id="proofBuilderTitle">Complete a two-column proof</h2><p class="muted">Choose a proof exercise. The givens and goal are provided; fill each blank with a statement and its reason.</p><div class="proof-exercise-controls"><label>Exercise<select id="proofExercise"></select></label><button class="btn" id="proofHint" type="button">Hint</button><button class="btn" id="proofReset" type="button">Reset proof</button></div><div class="proof-problem"><div><small>GIVEN</small><p id="proofGiven"></p></div><div><small>PROVE</small><p id="proofGoal"></p></div></div><table class="proof-table"><thead><tr><th>#</th><th>Statement</th><th>Reason</th></tr></thead><tbody id="proofSteps"></tbody></table><div id="proofStatus" class="feedback neutral" aria-live="polite">Fill in each proof row, then check your work.</div><div class="proof-actions"><button class="btn primary" id="proofCheck" type="button">Check proof</button><button class="btn" id="proofShow" type="button">Show one solution</button></div>`;
    document.querySelector('#qaSection')?.after(section);
    const proofModules = new Set(['geometry-2-5','geometry-2-6','geometry-3-3','geometry-3-4','geometry-review-2','geometry-reference']);
    const syncAvailability = () => { const selected = [...document.querySelectorAll('[data-geometry-module]:checked')].map((box) => box.dataset.geometryModule); section.hidden = !selected.some((key) => proofModules.has(key)); };
    syncAvailability();
    app.syncProofBuilderAvailability = syncAvailability;
    window.addEventListener('learning-modules-changed', syncAvailability);
    document.addEventListener('change', (event) => { if (event.target.matches?.('[data-geometry-module]')) requestAnimationFrame(syncAvailability); }, true);
    const exercises = [
      { title:'Congruent segments', given:['AB ≅ CD'], prove:'AB = CD', rows:[['AB ≅ CD','Given'],['AB = CD','Definition of Congruent Segments']], hint:'Convert segment congruence into equality of lengths using the definition of congruent segments.' },
      { title:'Midpoint segments', given:['M is the midpoint of AB'], prove:'AM ≅ MB', rows:[['M is the midpoint of AB','Given'],['AM = MB','Definition of Midpoint'],['AM ≅ MB','Definition of Congruent Segments']], hint:'A midpoint divides a segment into equal lengths; equal lengths determine congruent segments.' },
      { title:'Angle bisector', given:['BD bisects ∠ABC'], prove:'∠ABD ≅ ∠DBC', rows:[['BD bisects ∠ABC','Given'],['m∠ABD = m∠DBC','Definition of Angle Bisector'],['∠ABD ≅ ∠DBC','Definition of Congruent Angles']], hint:'An angle bisector creates two equal angle measures. Equal measures mean congruent angles.' },
      { title:'Vertical angles', given:['∠1 and ∠2 are vertical angles'], prove:'∠1 ≅ ∠2', rows:[['∠1 and ∠2 are vertical angles','Given'],['∠1 ≅ ∠2','Vertical Angle Theorem']], hint:'Use the Vertical Angle Theorem.' },
      { title:'Linear pair', given:['∠1 and ∠2 form a linear pair'], prove:'∠1 and ∠2 are supplementary', rows:[['∠1 and ∠2 form a linear pair','Given'],['∠1 and ∠2 are supplementary','Linear Pair Postulate']], hint:'Use the Linear Pair Postulate.' },
      { title:'Equal segments by transitivity', given:['AB = CD','CD = EF'], prove:'AB = EF', rows:[['AB = CD','Given'],['CD = EF','Given'],['AB = EF','Transitive Property of Equality']], hint:'Two quantities equal to the same quantity are equal to each other.' },
      { title:'Parallel lines and corresponding angles', given:['ℓ ∥ m','∠1 and ∠2 are corresponding angles'], prove:'∠1 ≅ ∠2', rows:[['ℓ ∥ m','Given'],['∠1 and ∠2 are corresponding angles','Given'],['∠1 ≅ ∠2','Corresponding Angles Postulate']], hint:'Parallel lines cut by a transversal have congruent corresponding angles.' },
      { title:'Perpendicular lines', given:['ℓ ⟂ m','∠1 and ∠2 are adjacent angles formed by ℓ and m'], prove:'∠1 and ∠2 are supplementary', rows:[['ℓ ⟂ m','Given'],['m∠1 = 90°','Definition of Perpendicular Lines'],['m∠2 = 90°','Definition of Perpendicular Lines'],['m∠1 + m∠2 = 180°','Substitution Property of Equality'],['∠1 and ∠2 are supplementary','Definition of Supplementary Angles']], hint:'Perpendicular lines create right angles. Add the two 90° measures.' }
    ];
    const reasons=['Given','Definition of Congruent Segments','Definition of Congruent Angles','Definition of Midpoint','Definition of Angle Bisector','Vertical Angle Theorem','Linear Pair Postulate','Transitive Property of Equality','Substitution Property of Equality','Corresponding Angles Postulate','Definition of Perpendicular Lines','Definition of Supplementary Angles'];
    const exerciseSelect=section.querySelector('#proofExercise'), givenNode=section.querySelector('#proofGiven'), goalNode=section.querySelector('#proofGoal'), body=section.querySelector('#proofSteps'), status=section.querySelector('#proofStatus');
    exercises.forEach((exercise,index)=>{const option=document.createElement('option');option.value=String(index);option.textContent=exercise.title;exerciseSelect.append(option);});
    const redraw=()=>{const exercise=exercises[Number(exerciseSelect.value)]||exercises[0];givenNode.textContent=exercise.given.join('; ');goalNode.textContent=exercise.prove;body.replaceChildren(...exercise.rows.map(([answer],index)=>{const row=document.createElement('tr');const number=document.createElement('td');number.textContent=String(index+1);const statementCell=document.createElement('td');const statement=document.createElement('input');statement.setAttribute('aria-label',`Statement for proof step ${index+1}`);statement.dataset.proofStatement='';statement.placeholder='Choose the justified statement';const reasonCell=document.createElement('td');const reason=document.createElement('select');reason.setAttribute('aria-label',`Reason for proof step ${index+1}`);reason.dataset.proofReason='';const blank=document.createElement('option');blank.value='';blank.textContent='Choose a reason';reason.append(blank);reasons.forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;reason.append(option);});statementCell.append(statement);reasonCell.append(reason);row.append(number,statementCell,reasonCell);return row;}));section.querySelectorAll('[data-proof-statement]').forEach((input,index)=>{input.value='';input.placeholder=index===0?`Start from a given (${exercise.rows[index][0]})`:'Enter the next justified statement';});status.className='feedback neutral';status.textContent=`Complete ${exercise.rows.length} proof steps. The givens and goal are provided.`;};
    exerciseSelect.addEventListener('change',redraw);section.querySelector('#proofReset').addEventListener('click',redraw);section.querySelector('#proofHint').addEventListener('click',()=>{status.className='feedback neutral';status.textContent=exercises[Number(exerciseSelect.value)].hint;});
    section.querySelector('#proofCheck').addEventListener('click',()=>{const expected=exercises[Number(exerciseSelect.value)].rows;const statements=[...body.querySelectorAll('[data-proof-statement]')];const rowReasons=[...body.querySelectorAll('[data-proof-reason]')];const normal=value=>normalizeAnswer(value);const missing=statements.some(input=>!input.value.trim())||rowReasons.some(select=>!select.value);if(missing){status.className='feedback bad';status.textContent='Complete every statement and choose a reason for every row.';return;}const correct=statements.every((input,index)=>normal(input.value)===normal(expected[index][0])&&rowReasons[index].value===expected[index][1]);status.className=`feedback ${correct?'good':'bad'}`;status.textContent=correct?'Correct proof. Every statement and reason matches a valid step.':'Not quite yet. Check the statements, reasons, and order. Use Hint for a clue or Show one solution to review the completed proof.';});
    section.querySelector('#proofShow').addEventListener('click',()=>{const exercise=exercises[Number(exerciseSelect.value)];body.querySelectorAll('[data-proof-statement]').forEach((input,index)=>input.value=exercise.rows[index][0]);body.querySelectorAll('[data-proof-reason]').forEach((select,index)=>select.value=exercise.rows[index][1]);status.className='feedback neutral';status.textContent='Solution shown. Reset proof to try this exercise again.';});redraw();
  }

  document.addEventListener('DOMContentLoaded', () => setTimeout(() => {
    const app = window.SpanishPracticeApp; if (!app) return; window.VertexApp = app; labels(); app.updateDocumentTitle = () => { document.title = 'Vertex — Accelerated Geometry'; }; const savedPreferences = readPreferences(); if (savedPreferences.modules) app.state.geometryModules = savedPreferences.modules; app.setLevel('geometry',{ historyMode:'replace' }); labels();
    const moduleParam = new URLSearchParams(location.search).get('modules');
    if (moduleParam !== null) { const chosen = new Set(moduleParam.split(',').filter((key) => byKey[key] && (!byKey[key].premium || app.hasPremiumAccess()))); app.state.geometryModules = Object.fromEntries(MODULES.map((module) => [module.key, chosen.has(module.key)])); writePreferences({ ...readPreferences(), modules:app.state.geometryModules }); }
    app.getEnabledModules = () => enabledKeys(app).filter((key) => app.state?.geometryModules?.[key] === true && poolFor(app,key).length);
    app.isModulePracticeEnabled = (key) => app.getEnabledModules().includes(key);
    app.getModuleCounts = (key) => ({ total:poolFor(app,key).length, available:poolFor(app,key).length });
    app.generateQuestion = (key) => { const pool = poolFor(app,key); if (!pool.length) return null; const item = pool[Math.floor(Math.random() * pool.length)]; return { ...item, module:key, acceptable:item.acceptable instanceof Set ? item.acceptable : answerSet([item.expectedDisplay]) }; };
    app.updateHomeSummary = () => { const node = document.getElementById('homeModuleSummary'); if (node) node.textContent = app.getEnabledModules().map((key) => byKey[key].name).join(', ') || 'No sections selected yet'; app.syncProofBuilderAvailability?.(); };
    app.getSessionTarget = () => app.hasPremiumAccess() ? 18 : 10;
    const originalRefresh = app.refreshSettingsUI.bind(app); app.refreshSettingsUI = (...args) => { const result = originalRefresh(...args); labels(); renderSettings(app); app.updateHomeSummary(); return result; };
    const originalRender = app.renderQuestion.bind(app); app.renderQuestion = (question, options) => { originalRender(question, options); const title = document.getElementById('qaTitle'); if (title) title.textContent = byKey[question?.module]?.name || 'Geometry'; document.getElementById('answerInput')?.setAttribute('placeholder','Type a geometry answer...'); const prompt = document.getElementById('qaPrompt'); let coach = document.getElementById('test2ScratchCoach'); if (question?.module === 'geometry-review-2' && prompt) { if (!coach) { coach = document.createElement('aside'); coach.id = 'test2ScratchCoach'; coach.className = 'test2-scratch-coach'; coach.setAttribute('aria-label','Scratch-paper-first test practice'); coach.innerHTML = '<strong>📝 Scratch paper first</strong><span>Write the slope, equation, distance setup, or angle relationship before you choose. Then submit to check your work and read the reasoning.</span>'; prompt.before(coach); } coach.hidden = false; } else if (coach) coach.hidden = true; };
    window.VertexMathAnswer = { normalize:normalizeAnswer, answerSet }; installMathKeyboard(); installProofBuilder(app); renderSettings(app); app.updateHomeSummary();
    app.runAutomatedChecks = () => { const results = MODULES.map((module) => ({ ok:(QUESTIONS[module.key] || []).length >= 6, label:`${module.name} has a varied question bank` })); results.push({ ok:MODULES.every((module) => module.sources.length > 0), label:'All modules retain PDF source references' }); results.push({ ok:MODULES.every((module) => (QUESTIONS[module.key] || []).some((question) => question.mode === 'mcq')), label:'Every geometry section offers an appropriate multiple-choice check' }); const test2 = QUESTIONS['geometry-review-2'] || []; results.push({ ok:test2.length >= 25 && test2.every((question) => question.mode === 'mcq' && question.options?.length === 4 && new Set(question.options).size === 4 && question.correctIndex >= 0 && question.correctIndex < 4 && question.explanation), label:'Test 2 review has varied four-choice questions with worked feedback' }); results.push({ ok:document.querySelector('.test2-review-module .module-practice-note')?.textContent.includes('Scratch-paper-first'), label:'Test 2 module explains the scratch-paper workflow' }); results.push({ ok:normalizeAnswer('  CONGRUENT   ANGLES. ') === 'congruent angles', label:'Answer normalization ignores case, spacing, and punctuation' }); results.push({ ok:normalizeAnswer('x + 2') === normalizeAnswer('x+2'), label:'Math answers accept harmless operator spacing' }); results.push({ ok:normalizeAnswer('-1') !== normalizeAnswer('1'), label:'Math normalization preserves meaningful signs' }); results.push({ ok:normalizeAnswer('√40') === 'sqrt 40' && normalizeAnswer('90°') === '90 degree', label:'Math notation normalization is installed' }); results.push({ ok:document.getElementById('proofBuilder')?.querySelectorAll('#proofExercise option').length >= 6 && document.getElementById('proofBuilder')?.querySelector('[data-proof-statement]'), label:'Guided proof exercises include given, prove, statements, and reasons' }); const output = document.getElementById('checksOutput'); if (output) { const passed = results.filter((item) => item.ok).length; output.className = `feedback ${passed === results.length ? 'good' : 'bad'}`; output.innerHTML = `${results.map((item) => `${item.ok ? '✓' : '✗'} ${item.label}`).join('<br>')}<br><small>Summary: ${passed}/${results.length} passed</small>`; } return { pass:results.filter((item) => item.ok).length, total:results.length, results }; };
    app.refreshSettingsUI();
  }, 0));
})();
